/**
 * Projectname Quản Lý Bán Vé Xem Phim
 * Package View.QLLC
 * ClassName ViewSuaLichChieu
 * @author RubikCrew
 * @Version 1.0 April 2013
 */

package View.QLLC;

import Model.LichChieu;
import Model.Phim;
import Model.PhongChieu;
import View.Main.MainView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Lớp ViewThemLichChieu hiển thị giao diện Thêm Lịch Chiếu 
 * Lớp ViewThemLichChieu được kế thừ từ lớp JFrame
 *
 * @author DANG.TH
 * @Version 1.0 April 2013
 */
public class ViewThemLichChieu extends javax.swing.JFrame {
    public DefaultTableModel model ;	
    public DefaultListModel listPhim;
    public DefaultListModel listPhong;
    
    /**
     * Creates new form ThemLichChieu
     */
    
    public ViewThemLichChieu() {
        initComponents();
        //Title
        this.setTitle("THÊM LỊCH CHIẾU - TRẦN HẢI ĐĂNG_TEAM 1");
        //set frame to Center Screen
        Toolkit theKit = this.getToolkit();
        Dimension wndSize = theKit.getScreenSize();
        this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
                wndSize.width / 2, wndSize.height / 2); // Size  

        //set icon
        try {
            BufferedImage image;
            image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
	
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
	
        this.setSize(1155,800);
        //viewlist = new ViewQlLC();
        model = (DefaultTableModel)tblLichChieu.getModel();
	listPhim = new DefaultListModel();
	listPhong = new DefaultListModel();
    }
    
    /*Sự kiện ấn nút Thêm Lịch Chiếu và Trở Về trên Giao Diện*/
    public void actionPeformed(ActionListener ac){
        btnTLC.addActionListener(ac);
        btnTV.addActionListener(ac);
    }
    
   /*Hiển thị một tin nhắn trên giao diện*/
   public void showMessage(String msg){
       JOptionPane.showMessageDialog(this, msg);
   }
   
   /*Hiển thị danh sách Lịch Chiếu lên Bảng Danh Sách Lịch Chiếu tlbLichChieu*/
   public void ShowDSLichChieu(List<LichChieu> list){
       model.fireTableDataChanged();
       model.getDataVector().removeAllElements();
     for(LichChieu l : list){
         model.addRow(new Object[]{l.getMalichchieu(),l.getPhim().getTenphim(),l.getPhong().getTenphong(),l.getNgaychieu(),l.getGiocchieu()});
     }  
   }
   
   /*Hiển thị danh sách Phim lên ListBox Phim listPhim*/
   public void ShowDSPhim(List<Phim> List){
	for (Phim p : List) {
	     listPhim.addElement(p.getMaphim()+" | "+p.getTenphim()+" | "+p.getDaodien()+" | "+p.getDienvien()+" | "+
		     p.getNamsx());
	}
	lbxPhim.setModel(listPhim);
   }
   
   /*Hiển thị danh sách phòng lên LisBox Phong listPhong*/
   public void ShowDSPhong(List<PhongChieu> List){
	for (PhongChieu ph : List) {
	     listPhong.addElement(ph.getMaphong()+" | "+ph.getTenphong()+" | "+ph.getTheloai()+" | "+ph.getSoluongghe());
	}
	lbxPhong.setModel(listPhong);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jScrollPhim = new javax.swing.JScrollPane();
          lbxPhim = new javax.swing.JList();
          jScrollPhong = new javax.swing.JScrollPane();
          lbxPhong = new javax.swing.JList();
          lbGioChieu = new javax.swing.JLabel();
          lbNgayChieu = new javax.swing.JLabel();
          txtMaLichChieu = new javax.swing.JTextField();
          txtNgayChieu = new javax.swing.JFormattedTextField();
          txtGioChieu = new javax.swing.JTextField();
          jCalendarButton1 = new org.sourceforge.jcalendarbutton.JCalendarButton();
          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tblLichChieu = new javax.swing.JTable();
          btnTLC = new javax.swing.JButton();
          btnTV = new javax.swing.JButton();
          bgR = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Thêm Lịch Chiếu");
          setBackground(new java.awt.Color(255, 255, 255));
          setMinimumSize(new java.awt.Dimension(1155, 780));
          setResizable(false);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          lbxPhim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
          lbxPhim.setModel(new javax.swing.AbstractListModel() {
               String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15", "Item 16", "Item 17", "Item 18", "Item 19", "Item 20" };
               public int getSize() { return strings.length; }
               public Object getElementAt(int i) { return strings[i]; }
          });
          jScrollPhim.setViewportView(lbxPhim);

          getContentPane().add(jScrollPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 110));

          lbxPhong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
          lbxPhong.setModel(new javax.swing.AbstractListModel() {
               String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15", "Item 16", "Item 17", "Item 18", "Item 19", "Item 20" };
               public int getSize() { return strings.length; }
               public Object getElementAt(int i) { return strings[i]; }
          });
          jScrollPhong.setViewportView(lbxPhong);

          getContentPane().add(jScrollPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 260, 110));

          lbGioChieu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          lbGioChieu.setText("Giờ Chiếu");
          getContentPane().add(lbGioChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

          lbNgayChieu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          lbNgayChieu.setText("Ngày Chiếu");
          getContentPane().add(lbNgayChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

          txtMaLichChieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
          txtMaLichChieu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
          txtMaLichChieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
          txtMaLichChieu.setEnabled(false);
          getContentPane().add(txtMaLichChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

          txtNgayChieu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat(""))));
          txtNgayChieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
          txtNgayChieu.setEnabled(false);
          txtNgayChieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
          getContentPane().add(txtNgayChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 170, 30));

          txtGioChieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
          getContentPane().add(txtGioChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, 220, 30));

          jCalendarButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/ico24MySche.png"))); // NOI18N
          jCalendarButton1.setText("");
          jCalendarButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
               public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    jCalendarButton1PropertyChange(evt);
               }
          });
          getContentPane().add(jCalendarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 40, 30));

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));

          jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

          tblLichChieu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
          tblLichChieu.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Mã Lịch Chiếu", "Phim", "Phòng Chiếu", "Ngày Chiếu", "Giờ Chiếu"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          tblLichChieu.setFillsViewportHeight(true);
          tblLichChieu.setGridColor(new java.awt.Color(0, 0, 0));
          tblLichChieu.setIntercellSpacing(new java.awt.Dimension(5, 5));
          jScrollPane1.setViewportView(tblLichChieu);

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
          );

          getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 810, 520));

          btnTLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTLC.png"))); // NOI18N
          btnTLC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTLC2.png"))); // NOI18N
          btnTLC.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnTLCActionPerformed(evt);
               }
          });
          getContentPane().add(btnTLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 710, 150, 40));

          btnTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnTV.png"))); // NOI18N
          btnTV.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnTV2.png"))); // NOI18N
          getContentPane().add(btnTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 710, 150, 40));

          bgR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/TLC.png"))); // NOI18N
          bgR.setText("jLabel1");
          bgR.setAlignmentY(0.0F);
          getContentPane().add(bgR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 790));

          pack();
     }// </editor-fold>//GEN-END:initComponents
     //Xử lý sự kiện ấn nút jCalendarButton1
     private void jCalendarButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarButton1PropertyChange
	  if(evt.getNewValue() instanceof Date){
	       txtNgayChieu.setText(dateFormat.format(evt.getNewValue()));
	  }
     }//GEN-LAST:event_jCalendarButton1PropertyChange

     private void btnTLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTLCActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_btnTLCActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel bgR;
     public javax.swing.JButton btnTLC;
     public javax.swing.JButton btnTV;
     private org.sourceforge.jcalendarbutton.JCalendarButton jCalendarButton1;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     public javax.swing.JScrollPane jScrollPhim;
     public javax.swing.JScrollPane jScrollPhong;
     private javax.swing.JLabel lbGioChieu;
     private javax.swing.JLabel lbNgayChieu;
     public javax.swing.JList lbxPhim;
     public javax.swing.JList lbxPhong;
     public javax.swing.JTable tblLichChieu;
     public javax.swing.JTextField txtGioChieu;
     public javax.swing.JTextField txtMaLichChieu;
     public javax.swing.JFormattedTextField txtNgayChieu;
     // End of variables declaration//GEN-END:variables
     SimpleDateFormat dateFormat;
}
