/**
 * Projectname Quản Lý Bán Vé Xem Phim
 * Package View.QLLC
 * ClassName ViewDSLichChieu
 * @author RubikCrew
 * @Version 1.0 April 2013
 */

package View.QLLC;
import Model.LichChieu;
import View.Main.MainView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;

/**
 * Giao diện QLLC hiển thị Danh sách lịch chiếu có trong CSDL và các chức năng
 * QLLC bao gồm: Thêm Lịch Chiếu, Sửa Lịch Chiếu, Xóa Lịch Chiếu, Tìm Kiếm Lịch
 * Chiếu
 * Lớp giao diện QLLC kế thừa lớp JFrame 
 * @author Dang.TH
 * @version 1.0 April 2013
 */

public class ViewDSLichChieu extends javax.swing.JFrame {
    
    public MainView mainview;		// Biến gọi giao diện chính
    public DefaultTableModel tmp;	// Biến model table
   
    /*Hàm khởi tạo một đối tượng giao diện QLLC */
    public ViewDSLichChieu() {
	//Title
        this.setTitle("QUẢN LÝ LỊCH CHIẾU - TRẦN HẢI ĐĂNG_TEAM 1");
        //set frame to Center Screen
        Toolkit theKit = this.getToolkit();
        Dimension wndSize = theKit.getScreenSize();
        this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
                wndSize.width / 2, wndSize.height / 2); // Size  

        //set icon
        try {
            BufferedImage image;
            image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } 
	dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        this.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          pnTKTenPhim = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          btnTK1 = new javax.swing.JButton();
          txtTenPhim = new javax.swing.JTextField();
          pnTKNgayChieu = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          txtNgayChieu = new javax.swing.JTextField();
          btnNgayChieu = new org.sourceforge.jcalendarbutton.JCalendarButton();
          btnTK2 = new javax.swing.JButton();
          pnTKGioChieu = new javax.swing.JPanel();
          jLabel4 = new javax.swing.JLabel();
          txtGioChieu = new javax.swing.JTextField();
          btnTK3 = new javax.swing.JButton();
          btnTLC = new javax.swing.JButton();
          btnSLC = new javax.swing.JButton();
          btnXLC = new javax.swing.JButton();
          btnTV = new javax.swing.JButton();
          jScrollPane2 = new javax.swing.JScrollPane();
          tblLC = new javax.swing.JTable();
          bgQLLC = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setBackground(new java.awt.Color(255, 255, 255));
          setMinimumSize(new java.awt.Dimension(1160, 770));
          setResizable(false);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          pnTKTenPhim.setBackground(new java.awt.Color(255, 255, 255));
          pnTKTenPhim.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Theo Tên Phim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

          jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
          jLabel1.setText("Tên Phim");

          btnTK1.setBackground(new java.awt.Color(10, 218, 245));
          btnTK1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
          btnTK1.setForeground(new java.awt.Color(255, 255, 255));
          btnTK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTimKiem.png"))); // NOI18N
          btnTK1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTimKiemB.png"))); // NOI18N

          javax.swing.GroupLayout pnTKTenPhimLayout = new javax.swing.GroupLayout(pnTKTenPhim);
          pnTKTenPhim.setLayout(pnTKTenPhimLayout);
          pnTKTenPhimLayout.setHorizontalGroup(
               pnTKTenPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pnTKTenPhimLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnTKTenPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(txtTenPhim)
                         .addGroup(pnTKTenPhimLayout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(0, 181, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTKTenPhimLayout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(btnTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
          );
          pnTKTenPhimLayout.setVerticalGroup(
               pnTKTenPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pnTKTenPhimLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE))
          );

          getContentPane().add(pnTKTenPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 160));

          pnTKNgayChieu.setBackground(new java.awt.Color(255, 255, 255));
          pnTKNgayChieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Theo Ngày Chiếu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
          pnTKNgayChieu.setAlignmentX(0.2F);
          pnTKNgayChieu.setAlignmentY(0.2F);

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
          jLabel2.setText("Ngày Chiếu");

          btnNgayChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/ico24MySche.png"))); // NOI18N
          btnNgayChieu.setText("");
          btnNgayChieu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
               public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    btnNgayChieuPropertyChange(evt);
               }
          });

          btnTK2.setBackground(new java.awt.Color(10, 218, 245));
          btnTK2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
          btnTK2.setForeground(new java.awt.Color(255, 255, 255));
          btnTK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTimKiem.png"))); // NOI18N
          btnTK2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTimKiemB.png"))); // NOI18N

          javax.swing.GroupLayout pnTKNgayChieuLayout = new javax.swing.GroupLayout(pnTKNgayChieu);
          pnTKNgayChieu.setLayout(pnTKNgayChieuLayout);
          pnTKNgayChieuLayout.setHorizontalGroup(
               pnTKNgayChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pnTKNgayChieuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnTKNgayChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(pnTKNgayChieuLayout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addGap(0, 0, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTKNgayChieuLayout.createSequentialGroup()
                              .addGroup(pnTKNgayChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(pnTKNgayChieuLayout.createSequentialGroup()
                                        .addComponent(txtNgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnNgayChieu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                   .addGroup(pnTKNgayChieuLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnTK2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(13, 13, 13)))
                    .addContainerGap())
          );
          pnTKNgayChieuLayout.setVerticalGroup(
               pnTKNgayChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pnTKNgayChieuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnTKNgayChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(btnNgayChieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(txtNgayChieu))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnTK2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE))
          );

          getContentPane().add(pnTKNgayChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 170));

          pnTKGioChieu.setBackground(new java.awt.Color(255, 255, 255));
          pnTKGioChieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Theo Giờ Chiếu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
          pnTKGioChieu.setAlignmentX(0.2F);
          pnTKGioChieu.setAlignmentY(0.2F);

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
          jLabel4.setText("Giờ Chiếu");

          btnTK3.setBackground(new java.awt.Color(10, 218, 245));
          btnTK3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
          btnTK3.setForeground(new java.awt.Color(255, 255, 255));
          btnTK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTimKiem.png"))); // NOI18N
          btnTK3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTimKiemB.png"))); // NOI18N

          javax.swing.GroupLayout pnTKGioChieuLayout = new javax.swing.GroupLayout(pnTKGioChieu);
          pnTKGioChieu.setLayout(pnTKGioChieuLayout);
          pnTKGioChieuLayout.setHorizontalGroup(
               pnTKGioChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pnTKGioChieuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnTKGioChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(pnTKGioChieuLayout.createSequentialGroup()
                              .addGap(0, 38, Short.MAX_VALUE)
                              .addComponent(jLabel4)
                              .addGap(153, 153, 153))
                         .addGroup(pnTKGioChieuLayout.createSequentialGroup()
                              .addComponent(txtGioChieu)
                              .addContainerGap())))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTKGioChieuLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTK3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );
          pnTKGioChieuLayout.setVerticalGroup(
               pnTKGioChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pnTKGioChieuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtGioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnTK3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE))
          );

          getContentPane().add(pnTKGioChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 270, 160));

          btnTLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTLC.png"))); // NOI18N
          btnTLC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          btnTLC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnTLC2.png"))); // NOI18N
          getContentPane().add(btnTLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 700, 150, 40));

          btnSLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnSLC.png"))); // NOI18N
          btnSLC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          btnSLC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnSLC2.png"))); // NOI18N
          getContentPane().add(btnSLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 700, 150, 40));

          btnXLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnXLC.png"))); // NOI18N
          btnXLC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          btnXLC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnXLC2.png"))); // NOI18N
          getContentPane().add(btnXLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, 150, 40));

          btnTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnTV.png"))); // NOI18N
          btnTV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          btnTV.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnTV2.png"))); // NOI18N
          getContentPane().add(btnTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, 150, 40));

          tblLC.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Mã Lịch Chiếu", "Tên Phim", "Tên Phòng", "Ngày Chiếu", "Giờ Chiếu"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          jScrollPane2.setViewportView(tblLC);

          getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 860, 520));

          bgQLLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BGQLLC.png"))); // NOI18N
          bgQLLC.setAlignmentY(0.0F);
          bgQLLC.setRequestFocusEnabled(false);
          bgQLLC.setVerifyInputWhenFocusTarget(false);
          getContentPane().add(bgQLLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 770));

          pack();
     }// </editor-fold>//GEN-END:initComponents
   //ActionPerformed
    public void actionPerformed(ActionListener ac){
        btnTLC.addActionListener(ac);	//Sự kiện bấm nút Thêm Lịch Chiếu
        btnSLC.addActionListener(ac);	//Sự kiện bấm nút Sửa Lịch Chiếu
        btnTV.addActionListener(ac);	//Sự kiện bấm nút Trở Về
	
    }
    // Sự kiên Xóa Lịch Chiếu
    public void XoaLcActionpeformed(ActionListener ac){
	 btnXLC.addActionListener(ac);
    }
    // Sự kiện Tìm kiếm
    public void TimKiemactionPeformed(ActionListener ac){
	btnTK1.addActionListener(ac);
	btnTK2.addActionListener(ac);
	btnTK3.addActionListener(ac);
    }
    //Hiển thị Danh sách lịch chiếu lên Bảng Danh sách lịch Chieu tblLC
    public void showDSLichChieu(List<LichChieu> List){
	tmp=(DefaultTableModel)tblLC.getModel();
        tmp.fireTableDataChanged();
        tmp.getDataVector().removeAllElements();
	 for (LichChieu lc : List) {
	     tmp.addRow(new Object[]{lc.getMalichchieu(),lc.getPhim().getTenphim(),
		  lc.getPhong().getTenphong(),lc.getNgaychieu(),lc.getGiocchieu()}); 
	 }
    }
    //Xử lý sự kiên bấm nút btnCalendar
    private void btnNgayChieuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnNgayChieuPropertyChange
        // TODO add your handling code here:
        if(evt.getNewValue() instanceof Date){
              txtNgayChieu.setText(dateFormat.format(evt.getNewValue()));
              System.out.println(dateFormat.format(evt.getNewValue()));
        }
      
    }//GEN-LAST:event_btnNgayChieuPropertyChange
    
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel bgQLLC;
     private org.sourceforge.jcalendarbutton.JCalendarButton btnNgayChieu;
     public javax.swing.JButton btnSLC;
     public javax.swing.JButton btnTK1;
     public javax.swing.JButton btnTK2;
     public javax.swing.JButton btnTK3;
     public javax.swing.JButton btnTLC;
     public javax.swing.JButton btnTV;
     public javax.swing.JButton btnXLC;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JPanel pnTKGioChieu;
     private javax.swing.JPanel pnTKNgayChieu;
     private javax.swing.JPanel pnTKTenPhim;
     public javax.swing.JTable tblLC;
     public javax.swing.JTextField txtGioChieu;
     public javax.swing.JTextField txtNgayChieu;
     public javax.swing.JTextField txtTenPhim;
     // End of variables declaration//GEN-END:variables
    SimpleDateFormat dateFormat;
}
