/**
 * Projectname Quản Lý Bán Vé Xem Phim
 * Package View.QLLC
 * ClassName ViewSuaLichChieu
 * @author RubikCrew
 * @Version 1.0 April 2013
 */

package View.QLLC;

import Model.LichChieu;
import Model.Phim;
import Model.PhongChieu;
import View.Main.MainView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Lớp giao diện Sửa lịch chiếu hiển thị giao diện sửa lịch chiếu Lớp giao diện
 * sửa lịch chiếu được kế thừ từ lớp JFrame
 *
 * @author DANG.TH
 * @Version 1.0 April 2013
 */
public class ViewSuaLichChieu extends javax.swing.JFrame {
     DefaultTableModel model=null;
     
     /**
      * Creates new form ViewSuaLichChieu
      */
     public ViewSuaLichChieu() {
	  initComponents();
	  model = new DefaultTableModel();
	  //Title
        this.setTitle("SỬA LỊCH CHIẾU - TRẦN HẢI ĐĂNG_TEAM 1");
        //set frame to Center Screen
        Toolkit theKit = this.getToolkit();
        Dimension wndSize = theKit.getScreenSize();
        this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
                wndSize.width / 2, wndSize.height / 2); // Size  

        //set icon
        try {
            BufferedImage image;
            image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
	  dateFormat = new SimpleDateFormat("dd/MM/yyyy");
	  this.setLocationRelativeTo(null);
	  JOptionPane.showMessageDialog(this,"Hãy chọn Lịch chiếu cần sửa trên Bảng!");
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          txtMaLichChieu = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          cboPhim = new javax.swing.JComboBox();
          jLabel3 = new javax.swing.JLabel();
          cboPhong = new javax.swing.JComboBox();
          jLabel4 = new javax.swing.JLabel();
          btnCalendar = new org.sourceforge.jcalendarbutton.JCalendarButton();
          jLabel5 = new javax.swing.JLabel();
          txtGioChieu = new javax.swing.JTextField();
          btnCapNhat = new javax.swing.JButton();
          btnTroVe = new javax.swing.JButton();
          txtNgayChieu = new javax.swing.JFormattedTextField();
          jPanel2 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tblLC = new javax.swing.JTable();
          bgSLC = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setMinimumSize(new java.awt.Dimension(930, 835));
          setPreferredSize(new java.awt.Dimension(930, 835));
          setResizable(false);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));
          jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

          jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          jLabel1.setText("Mã Lịch Chiếu");

          txtMaLichChieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
          txtMaLichChieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
          txtMaLichChieu.setEnabled(false);

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          jLabel2.setText("Phim Chiếu");

          cboPhim.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
          cboPhim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
          cboPhim.setLightWeightPopupEnabled(false);
          cboPhim.setRequestFocusEnabled(false);

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          jLabel3.setText("Phòng Chiếu");

          cboPhong.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
          cboPhong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          jLabel4.setText("Ngày Chiếu");

          btnCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/ico24MySche.png"))); // NOI18N
          btnCalendar.setText("");
          btnCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
               public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    btnCalendarPropertyChange(evt);
               }
          });

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          jLabel5.setText("Giờ Chiếu");

          txtGioChieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

          btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnUpdate.png"))); // NOI18N
          btnCapNhat.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/btnUpdate2.png"))); // NOI18N

          btnTroVe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          btnTroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnTV.png"))); // NOI18N
          btnTroVe.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/BtnTV2.png"))); // NOI18N

          txtNgayChieu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
          txtNgayChieu.setEnabled(false);
          txtNgayChieu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtMaLichChieu))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel3)
                                             .addComponent(jLabel2))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addGap(1, 1, 1)
                                                  .addComponent(cboPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addComponent(cboPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel5))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(txtGioChieu)
                                   .addComponent(txtNgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(26, 26, 26)
                              .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel1)
                                   .addComponent(txtMaLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel2)
                                             .addComponent(cboPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel3)))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                  .addComponent(jLabel4)
                                                  .addComponent(txtNgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel5)
                                             .addComponent(txtGioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                              .addGap(18, 18, 18)
                              .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
          );

          getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 910, 240));

          jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

          tblLC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          tblLC.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Mã Lịch Chiếu", "Phim", "Phòng Chiếu", "Ngày Chiếu", "Giờ Chiếu"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          tblLC.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblLCMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tblLC);

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
          );

          getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 910, 330));

          bgSLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/SLC.png"))); // NOI18N
          getContentPane().add(bgSLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 832));

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btnCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnCalendarPropertyChange
          // TODO add your handling code here:
	  if(evt.getNewValue() instanceof Date){
	       txtNgayChieu.setText(dateFormat.format(evt.getNewValue()));
	  }
     }//GEN-LAST:event_btnCalendarPropertyChange

     private void tblLCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLCMouseClicked
          // TODO add your handling code here:
	  int row = tblLC.getSelectedRow();
	  txtMaLichChieu.setText(tblLC.getValueAt(row, 0).toString());
	  txtNgayChieu.setText(tblLC.getValueAt(row,3).toString());
	  txtGioChieu.setText(tblLC.getValueAt(row, 4).toString());
     }//GEN-LAST:event_tblLCMouseClicked

     /*Sự kiện Bấm nút Cập Nhật và Trở Về trên giao diện*/
     public void SuaLichChieuListener(ActionListener ac){
	  btnCapNhat.addActionListener(ac);
	  btnTroVe.addActionListener(ac);
     }
     /*Hiển thị một tin nhắn trên giao diện*/
     public void showMessage(String msg){
       JOptionPane.showMessageDialog(this, msg);
     }
   
   /*Hiển thị bảng Danh Sách lịch Chiếu*/
   public void ShowDSLichChieu(List<LichChieu> list){
	  model = (DefaultTableModel)tblLC.getModel();
	  model.fireTableDataChanged();
	  model.getDataVector().removeAllElements();
	  for (LichChieu l : list) {
	       model.addRow(new Object[]{l.getMalichchieu(), l.getPhim().getTenphim(), l.getPhong().getTenphong(), l.getNgaychieu(), l.getGiocchieu()});
	  }	  
     }
   
   /*Load danh sach Phim lên ComboBox Phim cboPhim*/
   public void ShowDSPhim(List<Phim> List){
	DefaultComboBoxModel cboModel = new DefaultComboBoxModel();
	for (Phim p : List) {
	     cboModel.addElement(p.getMaphim()+" | "+p.getTenphim());
	}
	cboPhim.setModel(cboModel);
   }
   
   /*Load danh sach Phòng Chiếu lên ComboBox Phòng Chiếu cboPhong*/
   public void ShowDSPhong(List<PhongChieu> List){
	DefaultComboBoxModel cboModel = new DefaultComboBoxModel();
	for (PhongChieu ph : List) {
	     cboModel.addElement(ph.getMaphong()+" | "+ph.getTenphong());
	}
	cboPhong.setModel(cboModel);
   }
   
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel bgSLC;
     public org.sourceforge.jcalendarbutton.JCalendarButton btnCalendar;
     public javax.swing.JButton btnCapNhat;
     public javax.swing.JButton btnTroVe;
     public javax.swing.JComboBox cboPhim;
     public javax.swing.JComboBox cboPhong;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     public javax.swing.JTable tblLC;
     public javax.swing.JTextField txtGioChieu;
     public javax.swing.JTextField txtMaLichChieu;
     public javax.swing.JFormattedTextField txtNgayChieu;
     // End of variables declaration//GEN-END:variables
     SimpleDateFormat dateFormat;
}
