/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLBV;

import Controller.QLBV.ConnectDataBase;
import Model.Ve;
import View.Main.MainView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyendth92
 */
public class FQuanLyVe extends javax.swing.JFrame {

     ArrayList<Ve> dsVe;

     /**
      * Creates new form FQuanLyVe
      */
     public FQuanLyVe() {
	  //Title
	  this.setTitle("QUẢN LÝ BÁN VÉ - ĐÀO THÌ HUYỀN_TEAM 1");
	  //set frame to Center Screen
	  Toolkit theKit = this.getToolkit();
	  Dimension wndSize = theKit.getScreenSize();
	  this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
		  wndSize.width / 2, wndSize.height / 2); // Size  

	  //set icon
	  try {
	       BufferedImage image;
	       image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
	       this.setIconImage(image);
	  } catch (IOException ex) {
	       Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
	  }

	  initComponents();
	  TaoBangVe();
	  //SetTitle
	  this.setTitle("QUẢN LÝ BÁN VÉ");
     }

     /**
      * Ham hien thi danh sach Ve ra bang
      */
     public void TaoBangVe() {

	  dsVe = new ConnectDataBase().LayDsVe();
	  if (dsVe.size() == 0) {
	       JOptionPane.showMessageDialog(null, "Không có Vé nào trong CSDL!! Xin Cảm ơn");
	  } else {
	       DefaultTableModel m = (DefaultTableModel) tbVe.getModel();
	       m.fireTableDataChanged();
	       m.getDataVector().removeAllElements();
	       for (Ve i : dsVe) {
		    m.addRow(new Object[]{i.getMaVe(), i.getLichChieu().getMalichchieu(),
				 i.getLichChieu().getPhim().getTenphim(),
				 i.getLichChieu().getPhong().getTenphong(),
				 i.getLichChieu().getNgaychieu(), i.getLichChieu().getGiocchieu(),
				 i.getSoGhe(), i.getLoaiVe(),
				 i.getDonGia()});
	       }
	  }
     }

     /**
      * Hien thi danh sach Ve co trong CSDL
      */
     public void TaoBang() {
	  DefaultTableModel m = (DefaultTableModel) tbVe.getModel();
	  m.fireTableDataChanged();
	  m.getDataVector().removeAllElements();
	  for (Ve i : dsVe) {
	       m.addRow(new Object[]{i.getMaVe(), i.getLichChieu().getMalichchieu(),
			    i.getLichChieu().getPhim().getTenphim(),
			    i.getLichChieu().getPhong().getTenphong(),
			    i.getLichChieu().getNgaychieu(), i.getLichChieu().getGiocchieu(),
			    i.getSoGhe(), i.getLoaiVe(),
			    i.getDonGia()});
	  }
     }

     /**
      *
      */
     /**
      * Ham tim kiem doi tuong Ve
      *
      * @param maVe : maVe muon tim kiem
      * @return Ve
      */
     public Ve TkVe(int maVe) {
	  Ve ve = new Ve();
	  for (Ve i : dsVe) {
	       if (i.getMaVe() == maVe) {
		    ve = i;
	       }
	  }
	  return ve;
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          dl_InVe = new javax.swing.JDialog();
          jLabel19 = new javax.swing.JLabel();
          jLabel20 = new javax.swing.JLabel();
          lbl_MaVe = new javax.swing.JLabel();
          jLabel22 = new javax.swing.JLabel();
          jLabel23 = new javax.swing.JLabel();
          jLabel24 = new javax.swing.JLabel();
          jLabel25 = new javax.swing.JLabel();
          jButton7 = new javax.swing.JButton();
          lbl_TenPhim = new javax.swing.JLabel();
          lbl_TenPhong = new javax.swing.JLabel();
          lbl_NgayChieu = new javax.swing.JLabel();
          lbl_GioChieu = new javax.swing.JLabel();
          jLabel21 = new javax.swing.JLabel();
          jLabel26 = new javax.swing.JLabel();
          lbl_SoGhe = new javax.swing.JLabel();
          lbl_LoaiVe = new javax.swing.JLabel();
          jLabel29 = new javax.swing.JLabel();
          lbl_DonGia = new javax.swing.JLabel();
          lbl_NgayHT = new javax.swing.JLabel();
          jButton8 = new javax.swing.JButton();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          cbHT = new javax.swing.JComboBox();
          jScrollPane1 = new javax.swing.JScrollPane();
          tbVe = new javax.swing.JTable();
          jButton5 = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();
          jButton2 = new javax.swing.JButton();
          jButton1 = new javax.swing.JButton();
          jButton3 = new javax.swing.JButton();
          jButton4 = new javax.swing.JButton();
          jButton6 = new javax.swing.JButton();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          jLabel14 = new javax.swing.JLabel();
          jLabel15 = new javax.swing.JLabel();
          jLabel17 = new javax.swing.JLabel();
          jLabel18 = new javax.swing.JLabel();
          jLabel16 = new javax.swing.JLabel();
          jButton9 = new javax.swing.JButton();

          jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel19.setForeground(new java.awt.Color(255, 0, 0));
          jLabel19.setText("Thông Tin Vé");

          jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jLabel20.setText("Mã Vé");

          lbl_MaVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_MaVe.setForeground(new java.awt.Color(0, 0, 255));
          lbl_MaVe.setText("jLabel21");

          jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel22.setText("Tên Phim");

          jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel23.setText("Tên Phòng");

          jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel24.setText("Ngày Chiếu");

          jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel25.setText("Giờ Chiếu");

          jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jButton7.setForeground(new java.awt.Color(255, 0, 51));
          jButton7.setText("In Vé");
          jButton7.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
               }
          });

          lbl_TenPhim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_TenPhim.setForeground(new java.awt.Color(0, 0, 204));
          lbl_TenPhim.setText("jLabel26");

          lbl_TenPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_TenPhong.setForeground(new java.awt.Color(51, 0, 204));
          lbl_TenPhong.setText("jLabel27");

          lbl_NgayChieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_NgayChieu.setForeground(new java.awt.Color(51, 0, 204));
          lbl_NgayChieu.setText("jLabel28");

          lbl_GioChieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_GioChieu.setForeground(new java.awt.Color(51, 0, 204));
          lbl_GioChieu.setText("jLabel29");

          jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel21.setText("Vị Trí Ghế");

          jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel26.setText("Loại Vé");

          lbl_SoGhe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_SoGhe.setForeground(new java.awt.Color(51, 0, 204));
          lbl_SoGhe.setText("jLabel27");

          lbl_LoaiVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_LoaiVe.setForeground(new java.awt.Color(51, 0, 204));
          lbl_LoaiVe.setText("jLabel28");

          jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel29.setText("Thành Tiền");

          lbl_DonGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lbl_DonGia.setForeground(new java.awt.Color(51, 0, 204));
          lbl_DonGia.setText("jLabel30");

          lbl_NgayHT.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
          lbl_NgayHT.setText("jLabel27");

          jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jButton8.setForeground(new java.awt.Color(255, 0, 51));
          jButton8.setText("Tro Ve");
          jButton8.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout dl_InVeLayout = new javax.swing.GroupLayout(dl_InVe.getContentPane());
          dl_InVe.getContentPane().setLayout(dl_InVeLayout);
          dl_InVeLayout.setHorizontalGroup(
               dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(dl_InVeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel23)
                         .addComponent(jLabel24)
                         .addComponent(jLabel25)
                         .addComponent(jLabel21)
                         .addComponent(jLabel26)
                         .addComponent(jLabel29)
                         .addGroup(dl_InVeLayout.createSequentialGroup()
                              .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel20)
                                   .addComponent(jLabel22))
                              .addGap(69, 69, 69)
                              .addComponent(jLabel19))
                         .addGroup(dl_InVeLayout.createSequentialGroup()
                              .addGap(98, 98, 98)
                              .addComponent(jButton7)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_DonGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_TenPhim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_TenPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_NgayChieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_GioChieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_SoGhe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_LoaiVe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dl_InVeLayout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addGap(48, 48, 48)))))
                    .addContainerGap(27, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dl_InVeLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_NgayHT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );
          dl_InVeLayout.setVerticalGroup(
               dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(dl_InVeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel19)
                         .addComponent(lbl_NgayHT))
                    .addGap(36, 36, 36)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel20)
                         .addComponent(lbl_MaVe))
                    .addGap(41, 41, 41)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel22)
                         .addComponent(lbl_TenPhim))
                    .addGap(34, 34, 34)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel23)
                         .addComponent(lbl_TenPhong))
                    .addGap(30, 30, 30)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel24)
                         .addComponent(lbl_NgayChieu))
                    .addGap(32, 32, 32)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel25)
                         .addComponent(lbl_GioChieu))
                    .addGap(39, 39, 39)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel21)
                         .addComponent(lbl_SoGhe))
                    .addGap(40, 40, 40)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel26)
                         .addComponent(lbl_LoaiVe))
                    .addGap(36, 36, 36)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel29)
                         .addComponent(lbl_DonGia))
                    .addGap(41, 41, 41)
                    .addGroup(dl_InVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton7)
                         .addComponent(jButton8))
                    .addContainerGap(44, Short.MAX_VALUE))
          );

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jPanel1.setBackground(new java.awt.Color(255, 204, 204));

          jLabel1.setBackground(new java.awt.Color(0, 0, 255));
          jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(0, 0, 153));
          jLabel1.setText("QUẢN LÝ BÁN VÉ RẠP CHIẾU PHIM");

          jLabel2.setBackground(new java.awt.Color(51, 51, 255));
          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(255, 0, 51));
          jLabel2.setText("_____ Huyendth _____");

          jLabel3.setBackground(new java.awt.Color(0, 0, 255));
          jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jLabel3.setForeground(new java.awt.Color(0, 0, 102));
          jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Class_22.png"))); // NOI18N
          jLabel3.setText("Hiển Thị Theo :");

          cbHT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          cbHT.setForeground(new java.awt.Color(204, 0, 0));
          cbHT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã Vé", "Tên Phim", "Tên Phòng Chiếu" }));
          cbHT.addItemListener(new java.awt.event.ItemListener() {
               public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    cbHTItemStateChanged(evt);
               }
          });
          cbHT.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbHTActionPerformed(evt);
               }
          });

          tbVe.setBackground(new java.awt.Color(204, 255, 255));
          tbVe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          tbVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          tbVe.setForeground(new java.awt.Color(0, 0, 153));
          tbVe.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null}
               },
               new String [] {
                    "Mã Vé", "Mã Lịch Chiếu", "Tên Phim", "Tên Phòng", "Ngày Chiếu", "Giờ Chiếu", "Vị Trí Ghế", "Loại Vé", "Đơn giá"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
               };
               boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          tbVe.setGridColor(new java.awt.Color(0, 102, 51));
          tbVe.setOpaque(false);
          tbVe.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tbVeMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tbVe);
          tbVe.getColumnModel().getColumn(0).setResizable(false);
          tbVe.getColumnModel().getColumn(1).setResizable(false);
          tbVe.getColumnModel().getColumn(2).setResizable(false);
          tbVe.getColumnModel().getColumn(3).setResizable(false);
          tbVe.getColumnModel().getColumn(4).setResizable(false);
          tbVe.getColumnModel().getColumn(5).setResizable(false);
          tbVe.getColumnModel().getColumn(6).setResizable(false);
          tbVe.getColumnModel().getColumn(7).setResizable(false);
          tbVe.getColumnModel().getColumn(8).setResizable(false);

          jButton5.setBackground(new java.awt.Color(204, 0, 0));
          jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jButton5.setForeground(new java.awt.Color(0, 0, 153));
          jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset.png"))); // NOI18N
          jButton5.setText("Trở Về");
          jButton5.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
               }
          });

          jPanel2.setBackground(new java.awt.Color(0, 153, 102));

          jButton2.setBackground(new java.awt.Color(255, 255, 255));
          jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jButton2.setForeground(new java.awt.Color(0, 0, 102));
          jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sua.png"))); // NOI18N
          jButton2.setText("Sửa Vé");
          jButton2.setOpaque(false);
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jButton1.setBackground(new java.awt.Color(255, 255, 255));
          jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jButton1.setForeground(new java.awt.Color(0, 0, 102));
          jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_Application.png"))); // NOI18N
          jButton1.setText("Tạo Vé Mới");
          jButton1.setOpaque(false);
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jButton3.setBackground(new java.awt.Color(255, 255, 255));
          jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jButton3.setForeground(new java.awt.Color(0, 0, 102));
          jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trashcan_full.png"))); // NOI18N
          jButton3.setText("Xóa Vé");
          jButton3.setOpaque(false);
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          jButton4.setBackground(new java.awt.Color(255, 255, 255));
          jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jButton4.setForeground(new java.awt.Color(0, 0, 102));
          jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_accept.png"))); // NOI18N
          jButton4.setText("Cập Nhật");
          jButton4.setOpaque(false);
          jButton4.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
               }
          });

          jButton6.setBackground(new java.awt.Color(255, 255, 255));
          jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jButton6.setForeground(new java.awt.Color(0, 0, 102));
          jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/PhieuXuat.png"))); // NOI18N
          jButton6.setText("Thống Kê");
          jButton6.setOpaque(false);
          jButton6.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
          );

          jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLBV/1365018090_tickets.png"))); // NOI18N

          jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/christmas_tree256.png"))); // NOI18N

          jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/santa_claus256.png"))); // NOI18N

          jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/santa_claus256.png"))); // NOI18N

          jLabel11.setBackground(new java.awt.Color(255, 51, 0));

          jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icoHoliday_R.png"))); // NOI18N

          jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/santa_claus256.png"))); // NOI18N

          jButton9.setText("In Ve");
          jButton9.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton9ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(17, 17, 17))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                 .addGap(13, 13, 13)
                                                                 .addComponent(jLabel13)))
                                                       .addGap(18, 18, 18)
                                                       .addComponent(jLabel14)
                                                       .addGap(54, 54, 54)
                                                       .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                 .addGap(50, 50, 50)
                                                                 .addComponent(jLabel8)
                                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                 .addComponent(jLabel2)
                                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                 .addComponent(jLabel6))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                 .addGap(14, 14, 14)
                                                                 .addComponent(jLabel1)))
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                       .addComponent(jLabel9)
                                                       .addGap(140, 140, 140))
                                                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                       .addGap(469, 469, 469)
                                                       .addComponent(jLabel10)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                       .addComponent(jLabel16)))
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addGap(200, 200, 200)
                                                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addGap(45, 45, 45)
                                                  .addComponent(cbHT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addGap(48, 48, 48)
                                                  .addComponent(jLabel7)))
                                        .addGap(26, 26, 26)))))
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel14)
                                             .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addComponent(jLabel12)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(jLabel13))))
                                   .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(27, 27, 27))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                   .addComponent(jLabel9))
                              .addGap(17, 17, 17)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel7)
                         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(cbHT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel17)))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel18)))
                              .addContainerGap())
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel15))))
          );

          jLabel4.getAccessibleContext().setAccessibleParent(this);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     /*
      * Sap xep hien thi danh sach Ve theo 1. Ma Ve, 2. Ten Phim 3. Ten Phong
      */
    private void cbHTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHTItemStateChanged
	 if (cbHT.getSelectedIndex() == 0) {
	      Collections.sort(dsVe, new Comparator<Ve>() {
		   @Override
		   public int compare(Ve t, Ve t1) {
			return new Integer(t.getMaVe()).compareTo(t1.getMaVe());
		   }
	      });
	      TaoBang();
	 } else if (cbHT.getSelectedIndex() == 1) {
	      Collections.sort(dsVe, new Comparator<Ve>() {
		   @Override
		   public int compare(Ve t, Ve t1) {
			return t.getLichChieu().getPhim().getTenphim().compareTo(
				t1.getLichChieu().getPhim().getTenphim());

		   }
	      });
	      TaoBang();
	 } else {
	      Collections.sort(dsVe, new Comparator<Ve>() {
		   @Override
		   public int compare(Ve t, Ve t1) {
			return t.getLichChieu().getPhong().getTenphong().compareTo(
				t1.getLichChieu().getPhong().getTenphong());

		   }
	      });
	      TaoBang();
	 }
    }//GEN-LAST:event_cbHTItemStateChanged

     //Click nut Tao Ve moi! Form Tao Ve moi hien thi ra! 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	 FTaoVeMoi veMoi = new FTaoVeMoi();
	 veMoi.setVisible(true);
	 veMoi.setLocationRelativeTo(null);
	 dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     /*
      * Click nut Sua Ve! Lay thong tin ve da chon rui gui den form sua Ve
      */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	 try {
	      if (tbVe.getSelectedRowCount() == 0) {
		   JOptionPane.showMessageDialog(null, "Hãy chọn Ve cần sửa",
			   "     : : : Warning : : :", JOptionPane.ERROR_MESSAGE);
	      } else {
		   int row = tbVe.getSelectedRow();  // Hang duoc chon trong bang Vé\
		   Ve ve = TkVe(Integer.parseInt(tbVe.getValueAt(row, 0).toString()));
		   int j = JOptionPane.showConfirmDialog(null,
			   "Bạn chắc chắn muốn sửa thông tin Vé: " + ve.getMaVe(),
			   "::: Update Data ::: !", 2);
		   if (j == 0) {
			FSuaVe sua = new FSuaVe(ve);
			sua.setVisible(true);
			sua.setLocationRelativeTo(null);
			dispose();
		   }
	      }
	 } catch (Exception e) {
	      JOptionPane.showMessageDialog(rootPane, e.getMessage());
	 }
    }//GEN-LAST:event_jButton2ActionPerformed

     /*
      * click nut Xoa Ve! Ve duoc xoa khoi CSDL *
      */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	 try {
	      if (tbVe.getSelectedRowCount() == 0) {
		   JOptionPane.showMessageDialog(null, "Hãy chọn Ve cần xóa khỏi CSDL ",
			   "     : : : Warning : : :", JOptionPane.ERROR_MESSAGE);
	      } else {
		   int row = tbVe.getSelectedRow();  // Hang duoc chon trong bang Vé\
		   // Ve ve = TkVe(Integer.parseInt(tbVe.getValueAt(row, 0).toString())); 
		   int j = JOptionPane.showConfirmDialog(null,
			   "Bạn chắc chắn muốn xóa thông tin Vé này không? ",
			   "::: Update Data ::: !", 2);
		   if (j == 0) {
			new ConnectDataBase().XoaVe(Integer.parseInt(
				tbVe.getValueAt(row, 0).toString()));
			JOptionPane.showMessageDialog(null, "Xoa ve thanh cong!");
			TaoBangVe();

		   }


	      }
	 } catch (Exception e) {
	      JOptionPane.showMessageDialog(rootPane, e.getMessage());
	 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

     // Click nut Cap nhat! CSDL duoc cap nhat lai
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
	 TaoBangVe();
    }//GEN-LAST:event_jButton4ActionPerformed

     // Click de tro ve man hinh chuc nang chinh cua phan mem 
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	 new MainView().setVisible(true);
	 this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

     // Click nut Thong Ke --> Frame thong ke hien ra
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
	 FThongKe tKe = new FThongKe();
	 tKe.setVisible(true);
	 tKe.setLocationRelativeTo(null);
	 dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cbHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHTActionPerformed
	 // TODO add your handling code here:
    }//GEN-LAST:event_cbHTActionPerformed

     /**
      * In Thong tin Ve giao cho khach hang Khi click chon vao Ve trong bang
      */
    private void tbVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVeMouseClicked
    }//GEN-LAST:event_tbVeMouseClicked

     // In ve ra cho khach hang
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
	 // TODO add your handling code here:
	 //Xu ly cho thao tac in thong tin ve
	 dl_InVe.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

     /**
      * Tro ve giao dien quan ly Ve
      */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
	 // TODO add your handling code here:
	 dl_InVe.setVisible(false);

    }//GEN-LAST:event_jButton8ActionPerformed

     /**
      * In Ve ra cho khach hang
      */
     private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

	  try {
	       if (tbVe.getSelectedRowCount() == 0) {
		    JOptionPane.showMessageDialog(null, "Hãy chọn Ve cần In ra ",
			    "     : : : Warning : : :", JOptionPane.ERROR_MESSAGE);
	       } else {
		    int row = tbVe.getSelectedRow();  // Hang duoc chon trong bang Vé\
		    // Ve ve = TkVe(Integer.parseInt(tbVe.getValueAt(row, 0).toString())); 
		    int j = JOptionPane.showConfirmDialog(null,
			    "Bạn chắc chắn muốn In thông tin Vé này không? ",
			    "::: Update Data ::: !", 2);
		    if (j == 0) {


			 dl_InVe.setVisible(true);
			 dl_InVe.setLocationRelativeTo(null);
			 dl_InVe.pack();
			 dl_InVe.setLocation(300, 30);


			 lbl_MaVe.setText(tbVe.getValueAt(row, 0).toString());
			 lbl_TenPhim.setText(tbVe.getValueAt(row, 2).toString());
			 lbl_TenPhong.setText(tbVe.getValueAt(row, 3).toString());
			 lbl_NgayChieu.setText(tbVe.getValueAt(row, 4).toString());
			 lbl_GioChieu.setText(tbVe.getValueAt(row, 5).toString());
			 lbl_SoGhe.setText(tbVe.getValueAt(row, 6).toString());
			 lbl_LoaiVe.setText(tbVe.getValueAt(row, 7).toString());
			 lbl_DonGia.setText(tbVe.getValueAt(row, 8).toString());

			 Calendar cal = Calendar.getInstance();
			 SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
			 String date = dateformat.format(cal.getTime());

			 lbl_NgayHT.setText("Ngay :: " + date);
		    }


	       }
	  } catch (Exception e) {
	       JOptionPane.showMessageDialog(rootPane, e.getMessage());
	  }

     }//GEN-LAST:event_jButton9ActionPerformed
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JComboBox cbHT;
     private javax.swing.JDialog dl_InVe;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JButton jButton4;
     private javax.swing.JButton jButton5;
     private javax.swing.JButton jButton6;
     private javax.swing.JButton jButton7;
     private javax.swing.JButton jButton8;
     private javax.swing.JButton jButton9;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel20;
     private javax.swing.JLabel jLabel21;
     private javax.swing.JLabel jLabel22;
     private javax.swing.JLabel jLabel23;
     private javax.swing.JLabel jLabel24;
     private javax.swing.JLabel jLabel25;
     private javax.swing.JLabel jLabel26;
     private javax.swing.JLabel jLabel29;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JLabel lbl_DonGia;
     private javax.swing.JLabel lbl_GioChieu;
     private javax.swing.JLabel lbl_LoaiVe;
     private javax.swing.JLabel lbl_MaVe;
     private javax.swing.JLabel lbl_NgayChieu;
     private javax.swing.JLabel lbl_NgayHT;
     private javax.swing.JLabel lbl_SoGhe;
     private javax.swing.JLabel lbl_TenPhim;
     private javax.swing.JLabel lbl_TenPhong;
     private javax.swing.JTable tbVe;
     // End of variables declaration//GEN-END:variables
}
