/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLBV;

import Controller.QLBV.ConnectDataBase;
import Model.LichChieu;
import Model.Phim;
import Model.PhongChieu;
import Model.Ve;
import View.Main.MainView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyendth92
 */
public class FSuaVe extends javax.swing.JFrame {

     ArrayList<Phim> dsPhim = new ArrayList<>();
     ArrayList<LichChieu> dsLichChieu = new ArrayList<>();
     ArrayList<PhongChieu> dsPhongChieu = new ArrayList<>();
     ArrayList<Ve> dsVe = new ArrayList<>();
     Ve veCu = new Ve();
     Ve ve = new Ve();

     /**
      * Creates new form FSuaVe
      */
     public FSuaVe(Ve ve) {
	  //Title
	  this.setTitle("SỬA VÉ - ĐÀO THÌ HUYỀN_TEAM 1");
	  //set frame to Center Screen
	  Toolkit theKit = this.getToolkit();
	  Dimension wndSize = theKit.getScreenSize();
	  this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
		  wndSize.width / 2, wndSize.height / 2); // Size  

	  //set icon
	  try {
	       BufferedImage image;
	       image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
	       this.setIconImage(image);
	  } catch (IOException ex) {
	       Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
	  }
	  initComponents();
	  Init();
	  HienThi(ve.getLichChieu().getMalichchieu());
	  formatV();

	  lbl_MaLC.setText(Integer.toString(ve.getLichChieu().getMalichchieu()));
	  gheTrong(ve.getLichChieu().getMalichchieu());
	  cbSoGhe.setSelectedItem(Integer.toString(ve.getSoGhe()));
	  cbLoaiVe.setSelectedItem(ve.getLoaiVe());
	  txtDonGia.setText(Float.toString(ve.getDonGia()));

	  veCu = ve;
     }

     /*
      * Đọc dữ liệu từ CSDL gán vào cho các biến dsLichChieu, dsPhim, dsVe set
      * nội dung cho listPhim trong giao diện sửa Vé
      *
      */
     public void Init() {
	  // Doc danh sach Lich chieu tu CSDL 
	  dsLichChieu = new ConnectDataBase().LayDsLichChieu();
	  // Doc DS Phim tu CSDL 
	  dsPhim = new ConnectDataBase().LayDsPhim();
	  // Doc DS Ve co trong CSDL 
	  dsVe = new ConnectDataBase().LayDsVe();

	  String[] t = new String[dsPhim.size()];
	  for (int i = 0; i < dsPhim.size(); i++) {
	       t[i] = dsPhim.get(i).getTenphim();
	  }
	  listPhim.setModel(new DefaultComboBoxModel(t));
     }

     /*
      * Hàm tìm kiếm lịch chiếu theo Mã lịch chiếu @param maLichChieu chiếu Trả
      * về đối tượng lịch chiếu có mã trùng với mã lịch chiếu truyền vào
      */
     public LichChieu TimLichChieu(int maLichChieu) {
	  LichChieu lich = new LichChieu();

	  for (LichChieu i : dsLichChieu) {
	       if (i.getMalichchieu() == maLichChieu) {
		    lich = i;
	       }
	  }
	  return lich;
     }

     /**
      * Ham hien thi thong tin lich chieu cu Ve dang muon sua thong tin
      *
      * @param : maLC: ma lich chieu
      *
      */
     public void HienThi(int maLC) {
	  DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	  m.fireTableDataChanged();
	  m.getDataVector().removeAllElements();
	  LichChieu i = TimLichChieu(maLC);
	  m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
		       i.getPhong().getTenphong(),
		       i.getNgaychieu(), i.getGiocchieu()});
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel2 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          listPhim = new javax.swing.JList();
          jScrollPane2 = new javax.swing.JScrollPane();
          tbLC = new javax.swing.JTable();
          jScrollPane3 = new javax.swing.JScrollPane();
          listNgayChieu = new javax.swing.JList();
          jButton1 = new javax.swing.JButton();
          jButton5 = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jPanel1 = new javax.swing.JPanel();
          cbSoGhe = new javax.swing.JComboBox();
          txtDonGia = new javax.swing.JTextField();
          btTaoVe = new javax.swing.JButton();
          cbLoaiVe = new javax.swing.JComboBox();
          jLabel2 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          lbSoGhe = new javax.swing.JLabel();
          lbLoaiVe = new javax.swing.JLabel();
          lbDonGia = new javax.swing.JLabel();
          lbl_MaLC = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jPanel2.setBackground(new java.awt.Color(255, 204, 204));
          jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jPanel2.setForeground(new java.awt.Color(0, 0, 153));
          jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel2MouseClicked(evt);
               }
          });

          listPhim.setBackground(new java.awt.Color(255, 204, 153));
          listPhim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          listPhim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          listPhim.setForeground(new java.awt.Color(0, 0, 153));
          listPhim.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
               public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    listPhimValueChanged(evt);
               }
          });
          jScrollPane1.setViewportView(listPhim);

          tbLC.setBackground(new java.awt.Color(204, 255, 255));
          tbLC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          tbLC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          tbLC.setForeground(new java.awt.Color(0, 0, 102));
          tbLC.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Mã Lịch Chiêu", "Tên Phim", "Tên Phòng Chiếu", "Ngày Chiếu", "Giờ Chiếu"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          tbLC.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tbLCMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tbLC);

          listNgayChieu.setBackground(new java.awt.Color(255, 204, 153));
          listNgayChieu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          listNgayChieu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          listNgayChieu.setForeground(new java.awt.Color(0, 0, 153));
          listNgayChieu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
               public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    listNgayChieuValueChanged(evt);
               }
          });
          jScrollPane3.setViewportView(listNgayChieu);

          jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jButton1.setForeground(new java.awt.Color(0, 0, 102));
          jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/PhieuXuat.png"))); // NOI18N
          jButton1.setText("DS Lịch Chiếu");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jButton5.setBackground(new java.awt.Color(255, 0, 0));
          jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jButton5.setForeground(new java.awt.Color(0, 0, 102));
          jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset.png"))); // NOI18N
          jButton5.setText("Trở Về");
          jButton5.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(0, 0, 153));
          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Class_22.png"))); // NOI18N
          jLabel1.setText("TÌM KIẾM LỊCH CHIẾU");

          jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel6.setForeground(new java.awt.Color(0, 0, 102));
          jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LoaiDienThoai.png"))); // NOI18N
          jLabel6.setText("Tên Phim :");

          jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel4.setForeground(new java.awt.Color(0, 0, 153));
          jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gCalendar.png"))); // NOI18N
          jLabel4.setText("Ngày Chiếu :");

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane2)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(jLabel6)
                              .addGap(18, 18, 18)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                   .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(69, 69, 69)))
                    .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(220, 220, 220))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                              .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18))))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(35, 35, 35)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel6)
                                   .addComponent(jLabel4)))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(44, 44, 44)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(45, 45, 45)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          jPanel1.setBackground(new java.awt.Color(255, 204, 204));
          jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          jPanel1.setForeground(new java.awt.Color(0, 0, 153));

          cbSoGhe.setBackground(new java.awt.Color(255, 204, 204));
          cbSoGhe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          cbSoGhe.setForeground(new java.awt.Color(0, 0, 204));

          txtDonGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          txtDonGia.setForeground(new java.awt.Color(0, 0, 204));
          txtDonGia.setText(" ");

          btTaoVe.setBackground(new java.awt.Color(102, 102, 255));
          btTaoVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btTaoVe.setForeground(new java.awt.Color(0, 0, 153));
          btTaoVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Confirm.png"))); // NOI18N
          btTaoVe.setText("Sửa Vé");
          btTaoVe.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btTaoVeActionPerformed(evt);
               }
          });

          cbLoaiVe.setBackground(new java.awt.Color(153, 255, 255));
          cbLoaiVe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          cbLoaiVe.setForeground(new java.awt.Color(204, 0, 0));
          cbLoaiVe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIP", "Thường" }));

          jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(0, 0, 102));
          jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/48px-Crystal_Clear_app_korganizer.png"))); // NOI18N
          jLabel2.setText("SỬA THÔNG TIN VÉ MUA");

          jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel5.setForeground(new java.awt.Color(0, 0, 153));
          jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/internet_intranet.png"))); // NOI18N
          jLabel5.setText("Mã Lịch Chiếu :");

          lbSoGhe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          lbSoGhe.setForeground(new java.awt.Color(0, 0, 153));
          lbSoGhe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/GioiThieu_22.png"))); // NOI18N
          lbSoGhe.setText("Vị Trí Ghế :");

          lbLoaiVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          lbLoaiVe.setForeground(new java.awt.Color(0, 0, 102));
          lbLoaiVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/System_22.png"))); // NOI18N
          lbLoaiVe.setText(" Loại Vé :");

          lbDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          lbDonGia.setForeground(new java.awt.Color(0, 0, 102));
          lbDonGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ThuTien.png"))); // NOI18N
          lbDonGia.setText("Đơn Giá :");

          lbl_MaLC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          lbl_MaLC.setForeground(new java.awt.Color(0, 0, 204));
          lbl_MaLC.setText(" ");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(27, 27, 27)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(lbLoaiVe)
                                   .addComponent(lbSoGhe)
                                   .addComponent(lbDonGia))
                              .addGap(32, 32, 32)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(cbLoaiVe, 0, 286, Short.MAX_VALUE)
                                   .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(cbSoGhe, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(15, 15, 15)
                              .addComponent(jLabel5)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(lbl_MaLC, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addGap(94, 94, 94))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addComponent(btTaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(113, 113, 113))))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(58, 58, 58)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(lbl_MaLC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(66, 66, 66)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(cbSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(lbSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(cbLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(lbLoaiVe))
                    .addGap(49, 49, 49)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(lbDonGia))
                    .addGap(45, 45, 45)
                    .addComponent(btTaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     /**
      * set nội dung cho listNgayChieu khi kích chọn tên Phim trong list Phim
      * trong giao diên Sửa Vé
      */
    private void listPhimValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPhimValueChanged
	 String[] t = new String[dsLichChieu.size()];
	 for (int i = 0; i < dsLichChieu.size(); i++) {
	      if (dsLichChieu.get(i).getPhim().getTenphim().equals(
		      listPhim.getSelectedValue().toString())) {
		   t[i] = dsLichChieu.get(i).getNgaychieu();
	      }
	 }

	 listNgayChieu.setModel(new DefaultComboBoxModel(t));

	 // Bat su kien hien thi cho bang Lich Chieu khi chon ten Phim

	 DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	 m.fireTableDataChanged();
	 m.getDataVector().removeAllElements();


	 for (LichChieu i : dsLichChieu) {
	      if (i.getPhim().getTenphim().equals(listPhim.getSelectedValue().toString())) {

		   m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
				i.getPhong().getTenphong(),
				i.getNgaychieu(), i.getGiocchieu()});
	      }
	 }
   }//GEN-LAST:event_listPhimValueChanged
    private void tbLCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLCMouseClicked
	 int row = tbLC.getSelectedRow();  // Hang duoc chon trong bang Lich Chieu\



   }//GEN-LAST:event_tbLCMouseClicked
     /**
      * Bắt sự kiện khi thay đổi lựa chọn ngày chiếu trong listNgayChieu ở giao
      * diên tạo Vé Mơi
      */
    private void listNgayChieuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listNgayChieuValueChanged

	 DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	 m.fireTableDataChanged();
	 m.getDataVector().removeAllElements();
	 try {
	      for (LichChieu i : dsLichChieu) {
		   if (i.getNgaychieu().equals(listNgayChieu.getSelectedValue().toString())
			   && i.getPhim().getTenphim().equals(
			   listPhim.getSelectedValue().toString())) {

			m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
				     i.getPhong().getTenphong(),
				     i.getNgaychieu(), i.getGiocchieu()});
		   }
	      }
	 } catch (Exception e) {
	 }
   }//GEN-LAST:event_listNgayChieuValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	 new FQuanLyVe().setVisible(true);
	 dispose();
   }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
  }//GEN-LAST:event_jPanel2MouseClicked

     /**
      * Bắt sự kiện khi click nút Sửa Vé Cập nhật thông tin Vé vào CSDL
      */
    private void btTaoVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoVeActionPerformed
	 // TODO add your handling code here:
	 try {

	      if (txtDonGia.getText().equals("")) {
		   JOptionPane.showMessageDialog(null, "Cần nhập vào giá Vé !Xin cảm ơn!!!");
	      } else {
		   if (Float.parseFloat(txtDonGia.getText()) <= 0) {
			JOptionPane.showMessageDialog(null, "Giá vé phải là số dương!!!");
			txtDonGia.setText(null);
		   } else {
			//  Ve(LichChieu lichChieu, String loaiVe, int soGhe,
			//String loaiVe, float donGia)
			Ve ve = new Ve(TimLichChieu(Integer.parseInt(lbl_MaLC.getText().trim())),
				Integer.parseInt(cbSoGhe.getSelectedItem().toString()),
				cbLoaiVe.getSelectedItem().toString(),
				Float.parseFloat(txtDonGia.getText().trim()));
			dsVe.add(ve);
			if (new ConnectDataBase().SuaVe(ve, veCu) != 0) {
			     JOptionPane.showMessageDialog(rootPane, "Sửa vé thành công");
			     txtDonGia.setText(null);
			} else {
			     JOptionPane.showMessageDialog(rootPane, "Xảy ra lỗi trong quá trình sửa");
			}

		   }
	      }
	 } catch (Exception e) {
	      JOptionPane.showMessageDialog(null, "Nhâp sai định dạng giá vé! Xin cảm ơn");
	 }
    }//GEN-LAST:event_btTaoVeActionPerformed

     // Tai toan b0 danh sach lich chieu 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

	 DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	 m.fireTableDataChanged();
	 m.getDataVector().removeAllElements();


	 for (LichChieu i : dsLichChieu) {


	      m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
			   i.getPhong().getTenphong(),
			   i.getNgaychieu(), i.getGiocchieu()});

	 }
   }//GEN-LAST:event_jButton1ActionPerformed

     /**
      * Set không hiển thị các lable và ô số ghế, loại vém tổng tiền,,
      */
     public void format() {

	  lbSoGhe.setVisible(false);
	  cbSoGhe.setVisible(false);
	  lbLoaiVe.setVisible(false);
	  cbLoaiVe.setVisible(false);
	  lbDonGia.setVisible(false);
	  txtDonGia.setVisible(false);
	  btTaoVe.setVisible(false);

     }
     //Set hien thi cac o nhap du lieu thong tin cua Ve (Loai ve, Vi tri ngoi, don gia) khi 
     // Ma lich chieu da duoc kiem tra va nhan OK

     public void formatV() {

	  lbSoGhe.setVisible(true);
	  cbSoGhe.setVisible(true);
	  lbLoaiVe.setVisible(true);
	  cbLoaiVe.setVisible(true);
	  lbDonGia.setVisible(true);
	  txtDonGia.setVisible(true);
	  btTaoVe.setVisible(true);

     }

     /**
      * Hàm xác định dánh sách ghế trống của một phòng chiếu tại một thời điểm
      * xác định
      *
      * @param maLichChieu : maLC
      * @return noi dung cb So ghe chinh la danh sach ghe trong
      */
     public void gheTrong(int maLC) {
	  String[] t = new String[1000];

	  int i = 0;
	  for (int j = 1; j <= TimLichChieu(maLC).getPhong().getSoluongghe(); j++) {
	       int kt = 0;
	       for (Ve k : dsVe) {
		    if (k.getSoGhe() == j && k.getLichChieu().getMalichchieu() == maLC) {
			 kt = 1;
		    }
	       }
	       if (kt == 0) {
		    t[i] = Integer.toString(j);
		    i++;
	       }
	  }

	  cbSoGhe.setModel(new DefaultComboBoxModel(t));
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btTaoVe;
     private javax.swing.JComboBox cbLoaiVe;
     private javax.swing.JComboBox cbSoGhe;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton5;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane3;
     private javax.swing.JLabel lbDonGia;
     private javax.swing.JLabel lbLoaiVe;
     private javax.swing.JLabel lbSoGhe;
     private javax.swing.JLabel lbl_MaLC;
     private javax.swing.JList listNgayChieu;
     private javax.swing.JList listPhim;
     private javax.swing.JTable tbLC;
     private javax.swing.JTextField txtDonGia;
     // End of variables declaration//GEN-END:variables
}
