/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLBV;

import Controller.QLBV.ConnectDataBase;
import Model.LichChieu;
import Model.Phim;
import Model.PhongChieu;
import Model.Ve;
import View.Main.MainView;
import com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyendth92
 */
public class FTaoVeMoi extends javax.swing.JFrame {

     /*
      * Khai báo danh sách các thuộc tính
      */
     ArrayList<Phim> dsPhim = new ArrayList<>();
     ArrayList<LichChieu> dsLichChieu = new ArrayList<>();
     ArrayList<PhongChieu> dsPhongChieu = new ArrayList<>();
     ArrayList<Ve> dsVe = new ArrayList<>();
     Ve ve = new Ve(); // Khai baos mot doi tuong kieu la Ve

     /**
      * Creates new form FTaoVeMoi
      */
     public FTaoVeMoi() {
	  //Title
	  this.setTitle("TẠO VÉ MỚI - ĐÀO THÌ HUYỀN_TEAM 1");
	  //set frame to Center Screen
	  Toolkit theKit = this.getToolkit();
	  Dimension wndSize = theKit.getScreenSize();
	  this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
		  wndSize.width / 2, wndSize.height / 2); // Size  

	  //set icon
	  try {
	       BufferedImage image;
	       image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
	       this.setIconImage(image);
	  } catch (IOException ex) {
	       Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
	  }
	  initComponents();
	  init();
	  format();
     }

     public void init() {
	  // Doc danh sach Lich chieu tu CSDL 
	  dsLichChieu = new ConnectDataBase().LayDsLichChieu();
	  // Doc DS Phim tu CSDL 
	  dsPhim = new ConnectDataBase().LayDsPhim();
	  // Doc DS Ve co trong CSDL 
	  dsVe = new ConnectDataBase().LayDsVe();

	  String[] t = new String[dsPhim.size()];
	  for (int i = 0; i < dsPhim.size(); i++) {
	       t[i] = dsPhim.get(i).getTenphim();
	  }
	  listPhim.setModel(new DefaultComboBoxModel(t));
     }

     /**
      * Ham tra ve mot doi tuong la LichChieu Tham so truyen vao la ma lich
      * chieu
      */
     public LichChieu timLichChieu(int maLichChieu) {
	  LichChieu lich = new LichChieu();

	  // Duyet tu dau den cuoi danh sach lich chieu Neu lich chieu nao co ma
	  //trung voi ma mun tim thi gan lichchieu vua khoi tao bang lichchieu
	  // vua kiem tra

	  for (LichChieu i : dsLichChieu) {
	       if (i.getMalichchieu() == maLichChieu) {
		    lich = i;
	       }
	  }
	  return lich;
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel3 = new javax.swing.JLabel();
          jPanel2 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jScrollPane1 = new javax.swing.JScrollPane();
          listPhim = new javax.swing.JList();
          jScrollPane2 = new javax.swing.JScrollPane();
          tbLC = new javax.swing.JTable();
          jLabel4 = new javax.swing.JLabel();
          jScrollPane3 = new javax.swing.JScrollPane();
          listNgayChieu = new javax.swing.JList();
          jButton1 = new javax.swing.JButton();
          jButton5 = new javax.swing.JButton();
          jLabel6 = new javax.swing.JLabel();
          lbl_ThongTinVe = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          lbSoGhe = new javax.swing.JLabel();
          lbDonGia = new javax.swing.JLabel();
          txtMaLC = new javax.swing.JTextField();
          btOKLC = new javax.swing.JButton();
          cbSoGhe = new javax.swing.JComboBox();
          txtDonGia = new javax.swing.JTextField();
          btTaoVe = new javax.swing.JButton();
          lbLoaiVe = new javax.swing.JLabel();
          cbLoaiVe = new javax.swing.JComboBox();

          jLabel3.setText("jLabel3");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setBackground(new java.awt.Color(255, 204, 204));

          jPanel2.setBackground(new java.awt.Color(255, 204, 204));
          jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jPanel2MouseClicked(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(0, 0, 153));
          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Class_22.png"))); // NOI18N
          jLabel1.setText("TÌM KIẾM LỊCH CHIẾU");

          listPhim.setBackground(new java.awt.Color(255, 204, 153));
          listPhim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          listPhim.setForeground(new java.awt.Color(0, 51, 153));
          listPhim.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
               public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    listPhimValueChanged(evt);
               }
          });
          jScrollPane1.setViewportView(listPhim);

          tbLC.setBackground(new java.awt.Color(204, 255, 255));
          tbLC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
          tbLC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          tbLC.setForeground(new java.awt.Color(0, 0, 153));
          tbLC.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Mã Lịch Chiêu", "Tên Phim", "Tên Phòng Chiếu", "Ngày Chiếu", "Giờ Chiếu"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          tbLC.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tbLCMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tbLC);

          jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel4.setForeground(new java.awt.Color(0, 0, 153));
          jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gCalendar.png"))); // NOI18N
          jLabel4.setText("Ngày Chiếu :");

          listNgayChieu.setBackground(new java.awt.Color(255, 204, 153));
          listNgayChieu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          listNgayChieu.setForeground(new java.awt.Color(0, 0, 153));
          listNgayChieu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
               public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    listNgayChieuValueChanged(evt);
               }
          });
          jScrollPane3.setViewportView(listNgayChieu);

          jButton1.setBackground(new java.awt.Color(255, 255, 255));
          jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          jButton1.setForeground(new java.awt.Color(0, 0, 153));
          jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/PhieuXuat.png"))); // NOI18N
          jButton1.setText("DS Lịch Chiếu");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jButton5.setBackground(new java.awt.Color(255, 51, 51));
          jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jButton5.setForeground(new java.awt.Color(0, 0, 153));
          jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset.png"))); // NOI18N
          jButton5.setText("Trở Về");
          jButton5.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
               }
          });

          jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel6.setForeground(new java.awt.Color(0, 0, 102));
          jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LoaiDienThoai.png"))); // NOI18N
          jLabel6.setText("Tên Phim :");

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2))
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(18, 18, 18)
                              .addComponent(jLabel6)
                              .addGap(18, 18, 18)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(26, 26, 26)
                              .addComponent(jLabel4)
                              .addGap(18, 18, 18)
                              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 44, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(32, 32, 32)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                             .addGap(10, 10, 10)
                                             .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(56, 56, 56)
                              .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          lbl_ThongTinVe.setBackground(new java.awt.Color(255, 204, 204));

          jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(0, 0, 102));
          jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/48px-Crystal_Clear_app_korganizer.png"))); // NOI18N
          jLabel2.setText("THÔNG TIN VÉ");

          jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel5.setForeground(new java.awt.Color(0, 0, 153));
          jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/internet_intranet.png"))); // NOI18N
          jLabel5.setText("Mã Lịch Chiếu :");

          lbSoGhe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          lbSoGhe.setForeground(new java.awt.Color(0, 0, 153));
          lbSoGhe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/GioiThieu_22.png"))); // NOI18N
          lbSoGhe.setText("Vị Trí Ghế :");

          lbDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          lbDonGia.setForeground(new java.awt.Color(0, 0, 102));
          lbDonGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ThuTien.png"))); // NOI18N
          lbDonGia.setText("Đơn Giá :");

          txtMaLC.setText(" ");
          txtMaLC.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtMaLCMouseClicked(evt);
               }
          });
          txtMaLC.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtMaLCKeyPressed(evt);
               }
          });

          btOKLC.setBackground(new java.awt.Color(255, 51, 153));
          btOKLC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btOKLC.setForeground(new java.awt.Color(0, 0, 102));
          btOKLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ChapNhan.png"))); // NOI18N
          btOKLC.setText("OK");
          btOKLC.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btOKLCActionPerformed(evt);
               }
          });

          cbSoGhe.setBackground(new java.awt.Color(102, 102, 255));
          cbSoGhe.setForeground(new java.awt.Color(255, 0, 51));

          txtDonGia.setText(" ");

          btTaoVe.setBackground(new java.awt.Color(153, 153, 255));
          btTaoVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          btTaoVe.setForeground(new java.awt.Color(0, 0, 102));
          btTaoVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ChapNhan.png"))); // NOI18N
          btTaoVe.setText("Tạo Vé");
          btTaoVe.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btTaoVeActionPerformed(evt);
               }
          });

          lbLoaiVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          lbLoaiVe.setForeground(new java.awt.Color(0, 0, 102));
          lbLoaiVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/System_22.png"))); // NOI18N
          lbLoaiVe.setText(" Loại Vé :");

          cbLoaiVe.setBackground(new java.awt.Color(153, 153, 255));
          cbLoaiVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          cbLoaiVe.setForeground(new java.awt.Color(204, 0, 0));
          cbLoaiVe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIP", "Thường" }));
          cbLoaiVe.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbLoaiVeActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout lbl_ThongTinVeLayout = new javax.swing.GroupLayout(lbl_ThongTinVe);
          lbl_ThongTinVe.setLayout(lbl_ThongTinVeLayout);
          lbl_ThongTinVeLayout.setHorizontalGroup(
               lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ThongTinVeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(184, 184, 184))
               .addGroup(lbl_ThongTinVeLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel5)
                         .addComponent(lbSoGhe)
                         .addComponent(lbDonGia)
                         .addComponent(lbLoaiVe))
                    .addGap(27, 27, 27)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(cbSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(txtMaLC, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cbLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(106, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ThongTinVeLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ThongTinVeLayout.createSequentialGroup()
                              .addComponent(btOKLC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(202, 202, 202))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ThongTinVeLayout.createSequentialGroup()
                              .addComponent(btTaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(157, 157, 157))))
          );
          lbl_ThongTinVeLayout.setVerticalGroup(
               lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(lbl_ThongTinVeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(31, 31, 31)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(txtMaLC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(btOKLC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(cbSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(lbSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(42, 42, 42)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(lbLoaiVe)
                         .addComponent(cbLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(lbl_ThongTinVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(lbDonGia)
                         .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(56, 56, 56)
                    .addComponent(btTaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ThongTinVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbl_ThongTinVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     /**
      * Set noi dung cho ngay chieu khi kich chon vao Ten Phim
      */
    private void listPhimValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPhimValueChanged
	 String[] t = new String[dsLichChieu.size()];
	 for (int i = 0; i < dsLichChieu.size(); i++) {
	      if (dsLichChieu.get(i).getPhim().getTenphim().equals(
		      listPhim.getSelectedValue().toString())) {
		   t[i] = dsLichChieu.get(i).getNgaychieu();
	      }
	 }

	 listNgayChieu.setModel(new DefaultComboBoxModel(t));

	 // Bat su kien hien thi cho bang Lich Chieu khi chon ten Phim

	 DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	 m.fireTableDataChanged();
	 m.getDataVector().removeAllElements();


	 for (LichChieu i : dsLichChieu) {
	      if (i.getPhim().getTenphim().equals(listPhim.getSelectedValue().toString())) {

		   m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
				i.getPhong().getTenphong(),
				i.getNgaychieu(), i.getGiocchieu()});
	      }
	 }
    }//GEN-LAST:event_listPhimValueChanged

     /**
      * Set Text cho txtMaLC khi click chuot vao mot hang trong bang LichChieu
      */
    private void tbLCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLCMouseClicked
	 int row = tbLC.getSelectedRow();  // Hang duoc chon trong bang Lich Chieu\
	 txtMaLC.setText(tbLC.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tbLCMouseClicked
     /**
      * Bắt sự kiện khi thay đổi lựa chọn ngày chiếu trong listNgayChieu ở giao
      * diên tạo Vé Mơi
      */
    private void listNgayChieuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listNgayChieuValueChanged
	 DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	 m.fireTableDataChanged();
	 m.getDataVector().removeAllElements();
	 try {
	      for (LichChieu i : dsLichChieu) {
		   if (i.getNgaychieu().equals(listNgayChieu.getSelectedValue().toString())
			   && i.getPhim().getTenphim().equals(listPhim.getSelectedValue().toString())) {

			m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
				     i.getPhong().getTenphong(),
				     i.getNgaychieu(), i.getGiocchieu()});
		   }
	      }
	 } catch (Exception e) {
	 }
    }//GEN-LAST:event_listNgayChieuValueChanged
     /**
      * Hien thi toan bo lich Chieu len bang tbLC
      */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	 DefaultTableModel m = (DefaultTableModel) tbLC.getModel();
	 m.fireTableDataChanged();
	 m.getDataVector().removeAllElements();
	 for (LichChieu i : dsLichChieu) {
	      m.addRow(new Object[]{i.getMalichchieu(), i.getPhim().getTenphim(),
			   i.getPhong().getTenphong(),
			   i.getNgaychieu(), i.getGiocchieu()});
	 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
    }//GEN-LAST:event_jPanel2MouseClicked

     /**
      * Bắt sự kiện khi click nút OK Kt mã lịch chiếu! Nếu hết ghế trống đưa ra
      * thông báo Còn ghế trống hiển thị ô nhập vị trí ngồi và đơn giá
      */
    private void btOKLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKLCActionPerformed
	 // TODO add your handling code here:
	 try {
	      if (txtMaLC.getText().equals("")) {
		   JOptionPane.showMessageDialog(null, "Bạn cần nhập vào Mã Lịch Chiếu");
	      }
	      if (txtMaLC.getText() == null) {
		   JOptionPane.showMessageDialog(null, "Bạn cần nhập vào Mã Lịch Chiếu");
	      } else {
		   if (Integer.parseInt(txtMaLC.getText()) < 0) {
			JOptionPane.showMessageDialog(null, "Mã Lịch Chiếu phải là số nguyên dương");
			txtMaLC.setText(null);
		   } else {
			boolean ok = false;
			for (LichChieu i : dsLichChieu) {
			     if (i.getMalichchieu() == Integer.parseInt(txtMaLC.getText().trim())) {
				  ok = true;
			     }
			}
			if (ok) {
			     int soGhe = 0;
			     int kt = 0;
			     for (Ve t : dsVe) {
				  if (t.getLichChieu().getMalichchieu() == Integer.parseInt(
					  txtMaLC.getText().trim())) {
				       soGhe++;
				       ve = t;
				       kt = 1;
				  }
			     }
			     if (kt == 0) {
				  ve = null;
			     }
			     if (ve != null && soGhe == ve.getLichChieu().getPhong().getSoluongghe()) {
				  JOptionPane.showMessageDialog(null, "Đã hết ghế trống!!!!");

			     } else {
				  formatV();
				  gheTrong(Integer.parseInt(txtMaLC.getText().trim()));
			     }
			} else {
			     JOptionPane.showMessageDialog(null, "Không tồn tại lịch chiếu này! Xin cảm ơn");
			     txtMaLC.setText(null);
			}
		   }
	      }
	 } catch (Exception e) {
	      //JOptionPane.showMessageDialog(null, "Nhập sai định dạng");
	 }
    }//GEN-LAST:event_btOKLCActionPerformed
     /**
      * Bat su kien cua nut tao Ve Doc du lieu nhap vao tu ban phim roi them ve
      * vao CSDL Hiển Thị thông báo "Thêm vé thành công" khi vé được thêm vào
      * CSDL SetText cho txtMaLC và txtDonGia ve null
      */
    private void btTaoVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoVeActionPerformed
	 // TODO add your handling code here:
	 try {

	      if (txtDonGia.getText().equals("")) {
		   JOptionPane.showMessageDialog(null, "Cần Nhập Giá Vé! Xin cảm ơn!!!");
	      } else {
		   if (Float.parseFloat(txtDonGia.getText()) <= 0) {
			JOptionPane.showMessageDialog(null, "Giá vé phải là số dương!!!");
			txtDonGia.setText(null);
		   } else {
			//  Ve(LichChieu lichChieu, String loaiVe, int soGhe, float donGia)
			Ve ve = new Ve(timLichChieu(Integer.parseInt(txtMaLC.getText().trim())),
				Integer.parseInt(cbSoGhe.getSelectedItem().toString()),
				cbLoaiVe.getSelectedItem().toString(),
				Float.parseFloat(txtDonGia.getText().trim()));

			dsVe.add(ve);
			new ConnectDataBase().ThemVe(ve);
			// Them ve vao CSDL
			JOptionPane.showMessageDialog(null, "Thêm vé Thành công!!!  ");

			txtMaLC.setText(null);
			txtDonGia.setText(null);

		   }
	      }
	 } catch (Exception e) {
	      JOptionPane.showMessageDialog(null, "Nhập sai định dạng đơn giá! Xin cảm ơn");
	 }
    }//GEN-LAST:event_btTaoVeActionPerformed

     /**
      * Bắt sự kiện không cho phép hiển thị ô số ghế, loại vé, đơn giá khi nhập
      * mã lịch chiếu vào ô txtMaLC
      */
    private void txtMaLCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaLCKeyPressed
	 format();
	 btOKLC.setVisible(true);              // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLCKeyPressed

     /**
      * Bắt sự kiện không cho phép hiển thị ô số ghế, loại vé, đơn giá khi kích
      * chuột ô txtMaLC
      */
    private void txtMaLCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaLCMouseClicked
	 format();
	 btOKLC.setVisible(true);
    }//GEN-LAST:event_txtMaLCMouseClicked

    private void cbLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiVeActionPerformed
	 // TODO add your handling code here:
    }//GEN-LAST:event_cbLoaiVeActionPerformed

     /**
      * Trở về giao diện quản lý Vé khi click nút "Trở Về" trong giao diện
      * TạoVeMoi
      */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	 new FQuanLyVe().setVisible(true); // Cho phep hien thi form QuanLyVE
	 dispose();//Dong form hien tai
    }//GEN-LAST:event_jButton5ActionPerformed

     /**
      * Hàm xác định dánh sách ghế trống của một phòng chiếu tại một thời điểm
      * xác định Tra ve noi dung cb So ghe chinh la danh sach ghe trong
      */
     public void gheTrong(int maLC) {
	  String[] t = new String[1000];

	  int i = 0;
	  for (int j = 1; j <= timLichChieu(maLC).getPhong().getSoluongghe(); j++) {
	       int kt = 0;
	       for (Ve k : dsVe) {
		    if (k.getLichChieu().getMalichchieu() == maLC && k.getSoGhe() == j) {
			 kt = 1;
		    }
	       }
	       if (kt == 0) {
		    t[i] = Integer.toString(j);
		    i++;
	       }
	  }
	  cbSoGhe.setModel(new DefaultComboBoxModel(t));
     }

     /**
      * Set không hiển thị các lable và ô số ghế, loại vém tổng tiền,,
      */
     public void format() {

	  lbSoGhe.setVisible(false);
	  cbSoGhe.setVisible(false);
	  lbLoaiVe.setVisible(false);
	  cbLoaiVe.setVisible(false);
	  lbDonGia.setVisible(false);
	  txtDonGia.setVisible(false);
	  btTaoVe.setVisible(false);

     }
     //Set hien thi cac o nhap du lieu thong tin cua Ve (Loai ve, Vi tri ngoi, don gia) khi 
     // Ma lich chieu da duoc kiem tra va nhan OK

     public void formatV() {

	  lbSoGhe.setVisible(true);
	  cbSoGhe.setVisible(true);
	  lbLoaiVe.setVisible(true);
	  cbLoaiVe.setVisible(true);
	  lbDonGia.setVisible(true);
	  txtDonGia.setVisible(true);
	  btTaoVe.setVisible(true);

	  btOKLC.setVisible(false);
     }
     /**
      * @param args the command line arguments
      */
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btOKLC;
     private javax.swing.JButton btTaoVe;
     private javax.swing.JComboBox cbLoaiVe;
     private javax.swing.JComboBox cbSoGhe;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton5;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane3;
     private javax.swing.JLabel lbDonGia;
     private javax.swing.JLabel lbLoaiVe;
     private javax.swing.JLabel lbSoGhe;
     private javax.swing.JPanel lbl_ThongTinVe;
     private javax.swing.JList listNgayChieu;
     private javax.swing.JList listPhim;
     private javax.swing.JTable tbLC;
     private javax.swing.JTextField txtDonGia;
     private javax.swing.JTextField txtMaLC;
     // End of variables declaration//GEN-END:variables
}
