/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLBV;

import Controller.QLBV.ConnectDataBase;
import Model.LichChieu;
import Model.Phim;
import Model.PhongChieu;
import Model.Ve;
import View.Main.MainView;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyendth92
 */
public class FThongKe extends javax.swing.JFrame {

    ArrayList<Phim> dsPhim = new ArrayList<>();
    ArrayList<LichChieu> dsLichChieu = new ArrayList<>();
    ArrayList<PhongChieu> dsPhongChieu = new ArrayList<>();
    ArrayList<Ve> dsVe = new ArrayList<>();

    /**
     * Creates new form FThongKe
     */
    public FThongKe() {
        //Title
        this.setTitle("THỐNG KÊ - ĐÀO THÌ HUYỀN_TEAM 1");
        //set frame to Center Screen
        Toolkit theKit = this.getToolkit();
        Dimension wndSize = theKit.getScreenSize();
        this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
                wndSize.width / 2, wndSize.height / 2); // Size  

        //set icon
        try {
            BufferedImage image;
            image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        init();
    }

    public void init() {
        // Doc danh sach Lich chieu tu CSDL 
        dsLichChieu = new ConnectDataBase().LayDsLichChieu();
        // Doc DS Phim tu CSDL 
        dsPhim = new ConnectDataBase().LayDsPhim();
        // Doc DS Ve co trong CSDL 
        dsVe = new ConnectDataBase().LayDsVe();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbThongKe = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTK = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTK = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ThuTien.png"))); // NOI18N
        jLabel1.setText("THỐNG KÊ DOANH THU ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/PhieuXuat.png"))); // NOI18N
        jLabel2.setText("Thống Kê Theo :");

        cbThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbThongKe.setForeground(new java.awt.Color(255, 51, 51));
        cbThongKe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tên Phim", "Tên Phòng" }));
        cbThongKe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThongKeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/317.png"))); // NOI18N
        jLabel3.setText("Danh Sách :");

        listTK.setBackground(new java.awt.Color(255, 153, 153));
        listTK.setForeground(new java.awt.Color(0, 0, 102));
        listTK.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTKValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTK);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset.png"))); // NOI18N
        jButton1.setText("Trở Về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbTK.setBackground(new java.awt.Color(204, 255, 255));
        tbTK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbTK.setForeground(new java.awt.Color(0, 0, 153));
        tbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Tổng Số Vé Bán Ra", "Doanh Thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbTK);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tke.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(386, 386, 386))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bắt sư kiện khi click chọn hình thức thống kê
     */
    private void cbThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThongKeActionPerformed

        // TODO add your handling code here:
        if (cbThongKe.getSelectedIndex() == 0) {
            String t[] = new String[dsLichChieu.size()];

            for (int i = 0; i < dsLichChieu.size(); i++) {
                t[i] = dsLichChieu.get(i).getPhim().getTenphim();
            }
            listTK.setModel(new DefaultComboBoxModel(t));
        } else {
            String t[] = new String[dsLichChieu.size()];

            for (int i = 0; i < dsLichChieu.size(); i++) {
                t[i] = dsLichChieu.get(i).getPhong().getTenphong();
            }
            listTK.setModel(new DefaultComboBoxModel(t));
        }
    }//GEN-LAST:event_cbThongKeActionPerformed

    private void listTKValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTKValueChanged
        try {
            int tongVe = 0;
            double tongTien = 0;
            Ve ve = new Ve();

            DefaultTableModel m = (DefaultTableModel) tbTK.getModel();
            m.fireTableDataChanged();
            m.getDataVector().removeAllElements();

            if (cbThongKe.getSelectedIndex() == 0) {
                for (Ve i : dsVe) {
                    if (i.getLichChieu().getPhim().getTenphim().equals(listTK.getSelectedValue().toString())) {
                        tongVe++;
                        tongTien = tongTien + i.getDonGia();
                        ve = i;
                    }
                }
                if (tongTien != 0) {
                    m.addRow(new Object[]{ve.getLichChieu().getPhim().getMaphim(), ve.getLichChieu().getPhim().getTenphim(),
                                tongVe, tongTien});
                } else {
                    JOptionPane.showMessageDialog(null, "Hiện tại chưa bán đc vé nào! Xin cảm ơn!!!");
                }

            } else {

                for (Ve i : dsVe) {
                    if (i.getLichChieu().getPhong().getTenphong().equals(listTK.getSelectedValue().toString())) {
                        tongVe++;
                        tongTien = tongTien + i.getDonGia();
                        ve = i;
                    }
                }

                if (tongTien != 0) {
                    m.addRow(new Object[]{ve.getLichChieu().getPhong().getMaphong(),
                                ve.getLichChieu().getPhong().getTenphong(), tongVe, tongTien});
                } else {
                    JOptionPane.showMessageDialog(null, "Hiện tại chưa bán đc vé nào! Xin cảm ơn!!!");
                }
            }
        } catch (Exception e) {
        }    }//GEN-LAST:event_listTKValueChanged

    /**
     * Hiển thị giao diện quản lý vé khi click nút Trở Về
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new FQuanLyVe().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbThongKe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listTK;
    private javax.swing.JTable tbTK;
    // End of variables declaration//GEN-END:variables
}
