/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLP;

import Controller.QLP.Business.AuthenticationBL;
import Model.Phim;
import View.Main.MainView;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TranHaiDang
 */
public final class ViewQLPHIM extends javax.swing.JFrame {

     private AuthenticationBL auth;
     ArrayList<Phim> listPhim = new ArrayList<>();
     Phim p;
     Statement st;
     ResultSet rs;

     /**
      * Creates new form ViewQLPHIM
      */
     public ViewQLPHIM() {
	  //Title
	  this.setTitle("QUẢN LÝ PHIM - PHẠM MINH TIẾN_TEAM 1");
	  //set frame to Center Screen
	  Toolkit theKit = this.getToolkit();
	  Dimension wndSize = theKit.getScreenSize();
	  this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
		  wndSize.width / 2, wndSize.height / 2); // Size  

	  //set icon
	  try {
	       BufferedImage image;
	       image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
	       this.setIconImage(image);
	  } catch (IOException ex) {
	       Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
	  }
	  initComponents();
	  auth = new AuthenticationBL();
	  listPhim = auth.dsPhim();

	  taoBangPhim();
     }

     public void taoBangPhim() {
	  listPhim = new AuthenticationBL().dsPhim();
	  if (listPhim.size() == 0) {
	       JOptionPane.showMessageDialog(null, "Không có Phim nào trong CSDL!! Xin Cảm ơn");
	  } else {
	       DefaultTableModel m = (DefaultTableModel) tblPhim.getModel();
	       m.getDataVector().removeAllElements();
	       m.fireTableDataChanged();
	       TableRowSorter sorter = new TableRowSorter(m);
	       tblPhim.setRowSorter(sorter);

	       for (Phim i : listPhim) {
		    m.addRow(i.toArray());
	       }
	  }
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          tbnTimkiem = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();
          txtPhim = new javax.swing.JTextField();
          jPanel5 = new javax.swing.JPanel();
          cbTheloai = new javax.swing.JComboBox();
          jScrollPane2 = new javax.swing.JScrollPane();
          tblPhim = new javax.swing.JTable();
          BtnTP = new javax.swing.JButton();
          BtnSP = new javax.swing.JButton();
          BtnXP = new javax.swing.JButton();
          BtnTV = new javax.swing.JButton();
          BGQLLC = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setBackground(new java.awt.Color(255, 255, 255));
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));

          tbnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/btnTimKiem.png"))); // NOI18N
          tbnTimkiem.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/btnTimKiemB.png"))); // NOI18N
          tbnTimkiem.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    tbnTimkiemActionPerformed(evt);
               }
          });

          jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm theo tên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 102, 204))); // NOI18N

          txtPhim.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          txtPhim.setForeground(new java.awt.Color(204, 204, 204));
          txtPhim.setText("Nhập thông tin phim ...");
          txtPhim.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtPhimMouseClicked(evt);
               }
          });
          txtPhim.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyReleased(java.awt.event.KeyEvent evt) {
                    txtPhimKeyReleased(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE))
          );

          jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm thể loại phim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 102, 204))); // NOI18N

          cbTheloai.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          cbTheloai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hành động", "Hài hước", "Tâm lý", "Viễn tưởng", "Hoạt hình" }));
          cbTheloai.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbTheloaiActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
          jPanel5.setLayout(jPanel5Layout);
          jPanel5Layout.setHorizontalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cbTheloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          jPanel5Layout.setVerticalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cbTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 1, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(tbnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(tbnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE))
          );

          getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 270, 470));

          tblPhim.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
          tblPhim.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Mã phim", "Tên phim", "Diễn viên", "Đạo diễn", "Năm sx", "Thời lượng", "Thể loại", "Giới thiệu"
               }
          ) {
               boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
               }
          });
          tblPhim.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblPhimMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tblPhim);

          getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 850, -1));

          BtnTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BtnTP.png"))); // NOI18N
          BtnTP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          BtnTP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BtnTP2.png"))); // NOI18N
          BtnTP.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnTPActionPerformed(evt);
               }
          });
          getContentPane().add(BtnTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 150, 40));

          BtnSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/btnSP.png"))); // NOI18N
          BtnSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          BtnSP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/btnSP2.png"))); // NOI18N
          BtnSP.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnSPActionPerformed(evt);
               }
          });
          getContentPane().add(BtnSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 150, 40));

          BtnXP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BtnXP.png"))); // NOI18N
          BtnXP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          BtnXP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BtnXP2.png"))); // NOI18N
          BtnXP.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnXPActionPerformed(evt);
               }
          });
          getContentPane().add(BtnXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 680, 150, 40));

          BtnTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BtnTV.png"))); // NOI18N
          BtnTV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          BtnTV.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BtnTV2.png"))); // NOI18N
          BtnTV.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnTVActionPerformed(evt);
               }
          });
          getContentPane().add(BtnTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 680, 150, 40));

          BGQLLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/BGQLP.png"))); // NOI18N
          getContentPane().add(BGQLLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 730));

          pack();
     }// </editor-fold>//GEN-END:initComponents
// Su kien Action cua them phim
    private void BtnTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTPActionPerformed
	 // TODO add your handling code here:
	 new ViewThemPhim().setVisible(true);
	 this.dispose();

    }//GEN-LAST:event_BtnTPActionPerformed
// Su kien Action cua sua phim
    private void BtnSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSPActionPerformed
	 // TODO add your handling code here:
	 if (tblPhim.getSelectedRow() == 0) {
	      JOptionPane.showMessageDialog(null, "Hãy chọn phim cần sửa.",
		      "     : : : Warning : : :", JOptionPane.ERROR_MESSAGE);
	 } else {
	      int row = tblPhim.getSelectedRow();
	      Phim phim = timPhim(tblPhim.getValueAt(row, 0).toString());
	      int j = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn sửa phim : "
		      + phim.getTenphim(), "::: Update Data ::: !", 2);
	      if (j == 0) {
		   new ViewSuaPhim(phim).setVisible(true);
		   this.dispose();
	      }
	 }
    }//GEN-LAST:event_BtnSPActionPerformed

    private void BtnTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTVActionPerformed
	 // TODO add your handling code here:
	 this.dispose();
	 new MainView().setVisible(true);
    }//GEN-LAST:event_BtnTVActionPerformed
// Su kien Action cua nut xoa phim
    private void BtnXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXPActionPerformed
	 // TODO add your handling code here:
	 if (tblPhim.getSelectedRowCount() == 0) {
	      JOptionPane.showMessageDialog(null, "Hãy chọn Phim cần xóa khỏi CSDL ",
		      "     : : : Warning : : :", JOptionPane.ERROR_MESSAGE);
	 } else {
	      int row = tblPhim.getSelectedRow();  // Hang duoc chon trong bang Vé\

	      int j = JOptionPane.showConfirmDialog(null,
		      "Bạn chắc chắn muốn xóa thông tin Phim này không? ",
		      "::: Update Data ::: !", 2);
	      if (j == 0) {
		   new AuthenticationBL().xoaPhim(Integer.parseInt(
			   tblPhim.getValueAt(row, 0).toString()));
		   JOptionPane.showMessageDialog(null, "Xoa phim thanh cong!");
		   taoBangPhim();

	      }
	 }
    }//GEN-LAST:event_BtnXPActionPerformed

    private void txtPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhimMouseClicked
	 // TODO add your handling code here:
	 txtPhim.setText("");
	 txtPhim.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtPhimMouseClicked

    private void tbnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnTimkiemActionPerformed
	 timTheloai();
    }//GEN-LAST:event_tbnTimkiemActionPerformed

    private void tblPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhimMouseClicked
	 // TODO add your handling code here:
	 if (evt.getClickCount() == 2) {
	      int row = tblPhim.getSelectedRow();
	      Phim p3 = timPhim(String.valueOf(tblPhim.getValueAt(row, 0)));
	      new ThongTinPhim(p3).setVisible(true);
	 }
    }//GEN-LAST:event_tblPhimMouseClicked

    private void cbTheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTheloaiActionPerformed
	 // TODO add your handling code here:
    }//GEN-LAST:event_cbTheloaiActionPerformed

    private void txtPhimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhimKeyReleased
	 TimKiemPhim();
    }//GEN-LAST:event_txtPhimKeyReleased
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel BGQLLC;
     private javax.swing.JButton BtnSP;
     private javax.swing.JButton BtnTP;
     private javax.swing.JButton BtnTV;
     private javax.swing.JButton BtnXP;
     private javax.swing.JComboBox cbTheloai;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel5;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTable tblPhim;
     private javax.swing.JButton tbnTimkiem;
     private javax.swing.JTextField txtPhim;
     // End of variables declaration//GEN-END:variables
// Dinh nghia doi tuong tim thong tin Phim

     public void TimKiemPhim() {
	  TableModel absModel = (TableModel) tblPhim.getModel();
	  TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(absModel);
	  tblPhim.setRowSorter(sorter);
	  String text = txtPhim.getText();
	  try {
	       sorter.setRowFilter(RowFilter.regexFilter(text));
	  } catch (PatternSyntaxException pse) {
	       System.err.println("Bad regex pattern");
	  }
     }

     public void timTheloai() {
	  TableModel absModel = (TableModel) tblPhim.getModel();
	  TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(absModel);
	  tblPhim.setRowSorter(sorter);
	  String text = cbTheloai.getSelectedItem().toString();
	  try {
	       sorter.setRowFilter(RowFilter.regexFilter(text));
	  } catch (PatternSyntaxException pse) {
	       System.err.println("Bad regex pattern");
	  }
     }

     public Phim timPhim(String maP) {//gui thong tin tu bang? = p truyen tham so
	  Phim ph = new Phim();
	  for (Phim i : listPhim) {//kiem tra thong tin phim trong list danh sach phim
	       if (i.getMaphim() == Integer.parseInt(maP)) {//so sanh 2 doi tuong neu 
		    ph = i;
	       }
	  }
	  return ph;
     }
}
//-----------------------------spam--------------------
//DefaultTableModel m = (DefaultTableModel) tblPhim.getModel();
//        m.getDataVector().removeAllElements();
//        m.fireTableDataChanged();
//        switch (cbPhim.getSelectedItem().toString()) {
//            case "Tên phim": {
//                for (Phim phim : listPhim) {
//                    if (txtPhim.getText().equalsIgnoreCase(phim.getTenphim())) {
//                        m.addRow(phim.toArray());
//                    }
//                }
//                break;
//            }
//            case "Diễn viên": {
//                for (Phim phim : listPhim) {
//                    if (txtPhim.getText().equalsIgnoreCase(phim.getDienvien())) {
//                        m.addRow(phim.toArray());
//                    }
//                }
//                break;
//            }
//            case "Đạo diễn": {
//                Phim p2 = timDaodien(txtPhim.getText());
//                m.addRow(p2.toArray());
//                break;
//            }
//        }
////Dinh nghia doi tuong tim kiem theo ten phim
//    public Phim timTenphim(String tenP) {
//        Phim t = new Phim();
//        for (Phim i : listPhim) {
//            if (i.getTenphim().indexOf(tenP) != -1) {
//                t = i;
//            }
//        }
//        return t;
//    }
//   private void txtPhimKeyPressed(java.awt.event.KeyEvent evt) {                                   
// TODO add your handling code here:
//        DefaultTableModel m = (DefaultTableModel) tblPhim.getModel();
//        m.fireTableDataChanged();
//        TableRowSorter trs = new TableRowSorter(m);
//        tblPhim.setRowSorter(trs);
//        if (String.valueOf(cbPhim.getSelectedItem()).equalsIgnoreCase("Tên phim")) {
//            trs.setRowFilter(RowFilter.regexFilter(txtPhim.getText(), 0));
//        } else if (String.valueOf(cbPhim.getSelectedItem()).equalsIgnoreCase("Diễn viên")) {
//            trs.setRowFilter(RowFilter.regexFilter(txtPhim.getText(), 1));
//        } else if (String.valueOf(cbPhim.getSelectedItem()).equalsIgnoreCase("Đạo diễn")) {
//            trs.setRowFilter(RowFilter.regexFilter(txtPhim.getText(), 2));
//        }
//        listPhim = new AuthenticationBL().dsPhim();
//        taoBangPhim();
//    }