/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLPC;

import Controller.QLP.Business.AuthenticationBL;
import Model.Phim;
import Model.PhongChieu;
import View.QLP.ViewQLPHIM;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ViewSuaPC extends javax.swing.JFrame {

    ArrayList<PhongChieu> listPC = new ArrayList<PhongChieu>();
    AuthenticationBL auth = new AuthenticationBL();
    PhongChieu newpc;
    PhongChieu oldpc;
    /**
     * Creates new form ViewSuaPC
     */
    public ViewSuaPC(PhongChieu pc) {
        initComponents();
        txtMaphongchieu.setText(String.valueOf(pc.getMaphong()));
        txtTenphongchieu.setText(pc.getTenphong());
        txtSoluongghe.setText(String.valueOf(pc.getSoluongghe()));
        txtTheloaiphong.setText(pc.getTheloai());

        listPC = auth.dsPhongChieu();
        oldpc = new PhongChieu();
        oldpc = pc;
    }

    private ViewSuaPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel4 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jButton2 = new javax.swing.JButton();
          jButton1 = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          txtTheloaiphong = new javax.swing.JTextField();
          txtSoluongghe = new javax.swing.JTextField();
          txtTenphongchieu = new javax.swing.JTextField();
          txtMaphongchieu = new javax.swing.JTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel4.setText("The loai phong");

          jLabel2.setText("Ten phong chieu");

          jLabel3.setText("So luong ghe");

          jButton2.setText("Huy");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jButton1.setText("Luu phong");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jLabel1.setText("Ma phong chieu");

          txtMaphongchieu.setEditable(false);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(19, 19, 19)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel3)
                                   .addComponent(jLabel2)
                                   .addComponent(jLabel1))
                              .addGap(45, 45, 45)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(txtTenphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(txtMaphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtSoluongghe, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTheloaiphong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(143, 143, 143)
                              .addComponent(jButton1)
                              .addGap(32, 32, 32)
                              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(64, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(txtMaphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(txtTenphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtSoluongghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtTheloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton1)
                         .addComponent(jButton2))
                    .addContainerGap(86, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        auth = new AuthenticationBL();
        newpc = new PhongChieu(Integer.parseInt(txtMaphongchieu.getText()), txtTenphongchieu.getText(), 
                Integer.parseInt(txtSoluongghe.getText()),txtTheloaiphong.getText());
        if (listPC.contains(newpc)) {
            JOptionPane.showMessageDialog(rootPane, "Mã phim đã tồn tại...");
        } else {
            listPC.add(newpc);
            if (auth.suaPC(newpc, oldpc) != 0) {
                JOptionPane.showMessageDialog(rootPane, "Sửa phim thành công");
            }
            this.dispose();
            new ViewQLPC().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // TODO add your handling code here:
	  this.dispose();
	  new ViewQLPC();
     }//GEN-LAST:event_jButton2ActionPerformed
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JTextField txtMaphongchieu;
     private javax.swing.JTextField txtSoluongghe;
     private javax.swing.JTextField txtTenphongchieu;
     private javax.swing.JTextField txtTheloaiphong;
     // End of variables declaration//GEN-END:variables
}
