/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QLPC;

import Controller.QLP.Business.AuthenticationBL;
import Model.PhongChieu;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ViewThemPC extends javax.swing.JFrame {
    private AuthenticationBL auth = new AuthenticationBL();
    ArrayList<PhongChieu> listPC = new ArrayList<>();
    PhongChieu pc;
    /**
     * Creates new form ViewThemPC
     */
    public ViewThemPC() {
        initComponents();
        listPC = auth.dsPhongChieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          txtMaphongchieu = new javax.swing.JTextField();
          txtTenphongchieu = new javax.swing.JTextField();
          txtSoluongghe = new javax.swing.JTextField();
          txtTheloaiphong = new javax.swing.JTextField();
          btnThemphongchieu = new javax.swing.JButton();
          btnCancel = new javax.swing.JButton();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          btnThemphongchieu.setText("Thêm PC");
          btnThemphongchieu.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnThemphongchieuActionPerformed(evt);
               }
          });

          btnCancel.setText("Cancel");
          btnCancel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
               }
          });

          jLabel3.setText("Số lượng ghế");

          jLabel4.setText("Thể loại phòng");

          jLabel1.setText("Mã phòng chiếu");

          jLabel2.setText("Tên phòng chiếu");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(52, 52, 52)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel3)
                                   .addComponent(jLabel2)
                                   .addComponent(jLabel1))
                              .addGap(27, 27, 27)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(txtMaphongchieu)
                                   .addComponent(txtTenphongchieu)
                                   .addComponent(txtSoluongghe)
                                   .addComponent(txtTheloaiphong, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(150, 150, 150)
                              .addComponent(btnThemphongchieu)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                              .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(70, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(txtMaphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(txtTenphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtSoluongghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtTheloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnThemphongchieu)
                         .addComponent(btnCancel))
                    .addContainerGap(90, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void btnThemphongchieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemphongchieuActionPerformed
        //nhung thong tin nhap vao cac text se duoc dua vao doi tuong.
        //vay phai khai bao 1 doi tuong truyen vao gia tri khoi tao
        pc = new PhongChieu(Integer.parseInt(txtMaphongchieu.getText()),txtTenphongchieu.getText(),
            Integer.parseInt(txtSoluongghe.getText()),txtTheloaiphong.getText());
        if (listPC.contains(pc)) {
            JOptionPane.showMessageDialog(rootPane, "Mã phong chieu đã tồn tại...");
        }else{
            listPC.add(pc);
            auth = new AuthenticationBL();
            auth.themPC(pc);
            JOptionPane.showMessageDialog(rootPane, "Đã thêm phong chieu vào csdl...");
            this.dispose();
            new ViewQLPC().setVisible(true);
        }
    }//GEN-LAST:event_btnThemphongchieuActionPerformed

     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
          // TODO add your handling code here:
	  this.dispose();
	  new ViewQLPC().setVisible(true);
     }//GEN-LAST:event_btnCancelActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnCancel;
     private javax.swing.JButton btnThemphongchieu;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JTextField txtMaphongchieu;
     private javax.swing.JTextField txtSoluongghe;
     private javax.swing.JTextField txtTenphongchieu;
     private javax.swing.JTextField txtTheloaiphong;
     // End of variables declaration//GEN-END:variables
}
