/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import Controller.QLP.Business.AuthenticationBL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author TranHaiDang
 */
public class Login extends javax.swing.JFrame {

    /**s
     * Creates new form Login
     */
    public Login() throws IOException {
        //Title
        this.setTitle("Login");
        //set frame to Center Screen
        Toolkit theKit = this.getToolkit();
        Dimension wndSize = theKit.getScreenSize();
        this.setBounds(wndSize.width / 3, wndSize.height / 3, // Position  
                wndSize.width / 2, wndSize.height / 2); // Size  
        BufferedImage image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
        this.setIconImage(image);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jProgressBar1 = new javax.swing.JProgressBar();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          txtUsername = new javax.swing.JTextField();
          btnLogin = new javax.swing.JButton();
          btnExit = new javax.swing.JButton();
          cbRemember = new javax.swing.JCheckBox();
          txtPassword = new javax.swing.JPasswordField();
          jLabel2 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setBackground(new java.awt.Color(255, 255, 255));
          setFocusable(false);
          setMinimumSize(new java.awt.Dimension(450, 280));
          setResizable(false);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));
          jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

          jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(51, 102, 255));
          jLabel1.setText("Username");

          jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel3.setForeground(new java.awt.Color(51, 102, 255));
          jLabel3.setText("Password");

          txtUsername.setText("admin");

          btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icoLogin_1.png"))); // NOI18N
          btnLogin.setText("Login");
          btnLogin.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnLoginActionPerformed(evt);
               }
          });

          btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icoExit.png"))); // NOI18N
          btnExit.setText("Exit");

          cbRemember.setBackground(new java.awt.Color(255, 255, 255));
          cbRemember.setText("Remember");
          cbRemember.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbRememberActionPerformed(evt);
               }
          });

          txtPassword.setText("123456");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                   .addComponent(jLabel3)
                                   .addGap(18, 18, 18)
                                   .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                   .addComponent(jLabel1)
                                   .addGap(18, 18, 18)
                                   .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(cbRemember)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(btnLogin)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btnExit)))
                    .addContainerGap(38, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnLogin)
                         .addComponent(btnExit)
                         .addComponent(cbRemember))
                    .addContainerGap())
          );

          getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 390, -1));

          jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/Login.png"))); // NOI18N
          getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void cbRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRememberActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            // TODO add your handling code here:
            AuthenticationBL auth = new AuthenticationBL();
            boolean a = false;
            a = auth.loginPhim(txtUsername.getText(), new String(txtPassword.getPassword()));
            if (a) {
                MainView p = null;
                p = new MainView();
                p.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR", "Sai Mat Khau", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnExit;
     private javax.swing.JButton btnLogin;
     private javax.swing.JCheckBox cbRemember;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JProgressBar jProgressBar1;
     private javax.swing.JPasswordField txtPassword;
     private javax.swing.JTextField txtUsername;
     // End of variables declaration//GEN-END:variables
}
