/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import View.QLBV.FQuanLyVe;
import View.QLP.ViewQLPHIM;
import View.QLPC.ViewQLPC;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author TranHaiDang
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainView() {

        //Title
        this.setTitle("HỆ THỐNG QUẢN LÝ BÁN VÉ XEM PHIM - RUBIKCREW_TEAM 1");
        //set frame to Center Screen
        Toolkit theKit = this.getToolkit();
        Dimension wndSize = theKit.getScreenSize();
        this.setBounds(wndSize.width / 11, wndSize.height / 11, // Position  
                wndSize.width / 2, wndSize.height / 2); // Size  

        //set icon
        try {
            BufferedImage image;
            image = ImageIO.read(this.getClass().getResource("/Images/Icons/icon232x32.png"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
	
	//Khoi tao  
        initComponents();
	
	setTimeSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btnPhim = new javax.swing.JButton();
          BtnPhong = new javax.swing.JButton();
          BtnLichChieu = new javax.swing.JButton();
          BtnVe = new javax.swing.JButton();
          BtnTienIch = new javax.swing.JButton();
          BtnLienHe = new javax.swing.JButton();
          lblTimeSystem = new javax.swing.JLabel();
          lblDateSystem = new javax.swing.JLabel();
          Bạckground = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setResizable(false);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          btnPhim.setBackground(new java.awt.Color(255, 255, 255));
          btnPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/p.png"))); // NOI18N
          btnPhim.setAlignmentY(0.0F);
          btnPhim.setAutoscrolls(true);
          btnPhim.setBorder(null);
          btnPhim.setContentAreaFilled(false);
          btnPhim.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
          btnPhim.setDoubleBuffered(true);
          btnPhim.setFocusCycleRoot(true);
          btnPhim.setFocusTraversalPolicyProvider(true);
          btnPhim.setHideActionText(true);
          btnPhim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
          btnPhim.setMaximumSize(new java.awt.Dimension(345, 130));
          btnPhim.setMinimumSize(new java.awt.Dimension(345, 130));
          btnPhim.setPreferredSize(new java.awt.Dimension(345, 132));
          btnPhim.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/p3.png"))); // NOI18N
          btnPhim.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHIM/p2.png"))); // NOI18N
          btnPhim.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPhimActionPerformed(evt);
               }
          });
          getContentPane().add(btnPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 350, 130));

          BtnPhong.setBackground(new java.awt.Color(255, 255, 255));
          BtnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPC/ph.png"))); // NOI18N
          BtnPhong.setAlignmentY(0.0F);
          BtnPhong.setBorder(null);
          BtnPhong.setBorderPainted(false);
          BtnPhong.setContentAreaFilled(false);
          BtnPhong.setMaximumSize(new java.awt.Dimension(341, 130));
          BtnPhong.setMinimumSize(new java.awt.Dimension(341, 130));
          BtnPhong.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPC/ph3.png"))); // NOI18N
          BtnPhong.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPC/ph2.png"))); // NOI18N
          BtnPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnPhongActionPerformed(evt);
               }
          });
          getContentPane().add(BtnPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 350, 130));

          BtnLichChieu.setBackground(new java.awt.Color(255, 255, 255));
          BtnLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/lc.png"))); // NOI18N
          BtnLichChieu.setAlignmentY(0.0F);
          BtnLichChieu.setBorder(null);
          BtnLichChieu.setBorderPainted(false);
          BtnLichChieu.setContentAreaFilled(false);
          BtnLichChieu.setMaximumSize(new java.awt.Dimension(341, 130));
          BtnLichChieu.setMinimumSize(new java.awt.Dimension(341, 130));
          BtnLichChieu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/lc3.png"))); // NOI18N
          BtnLichChieu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLLC/lc2.png"))); // NOI18N
          BtnLichChieu.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnLichChieuActionPerformed(evt);
               }
          });
          getContentPane().add(BtnLichChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 350, 130));

          BtnVe.setBackground(new java.awt.Color(255, 255, 255));
          BtnVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLBV/bv.png"))); // NOI18N
          BtnVe.setAlignmentY(0.0F);
          BtnVe.setBorder(null);
          BtnVe.setBorderPainted(false);
          BtnVe.setContentAreaFilled(false);
          BtnVe.setMaximumSize(new java.awt.Dimension(341, 130));
          BtnVe.setMinimumSize(new java.awt.Dimension(341, 130));
          BtnVe.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLBV/bv3.png"))); // NOI18N
          BtnVe.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLBV/bv2.png"))); // NOI18N
          BtnVe.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnVeActionPerformed(evt);
               }
          });
          getContentPane().add(BtnVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 350, 130));

          BtnTienIch.setBackground(new java.awt.Color(255, 255, 255));
          BtnTienIch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TI/ti.png"))); // NOI18N
          BtnTienIch.setAlignmentY(0.0F);
          BtnTienIch.setBorder(null);
          BtnTienIch.setBorderPainted(false);
          BtnTienIch.setContentAreaFilled(false);
          BtnTienIch.setMaximumSize(new java.awt.Dimension(341, 130));
          BtnTienIch.setMinimumSize(new java.awt.Dimension(341, 130));
          BtnTienIch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TI/ti3.png"))); // NOI18N
          BtnTienIch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TI/ti2.png"))); // NOI18N
          BtnTienIch.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnTienIchActionPerformed(evt);
               }
          });
          getContentPane().add(BtnTienIch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 350, 130));

          BtnLienHe.setBackground(new java.awt.Color(255, 255, 255));
          BtnLienHe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LH/lh.png"))); // NOI18N
          BtnLienHe.setAlignmentY(0.0F);
          BtnLienHe.setBorder(null);
          BtnLienHe.setBorderPainted(false);
          BtnLienHe.setContentAreaFilled(false);
          BtnLienHe.setMaximumSize(new java.awt.Dimension(341, 130));
          BtnLienHe.setMinimumSize(new java.awt.Dimension(341, 130));
          BtnLienHe.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LH/lh3.png"))); // NOI18N
          BtnLienHe.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LH/lh2.png"))); // NOI18N
          BtnLienHe.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnLienHeActionPerformed(evt);
               }
          });
          getContentPane().add(BtnLienHe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 350, 130));

          lblTimeSystem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          lblTimeSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          getContentPane().add(lblTimeSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 180, 60));
          getContentPane().add(lblDateSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 170, 30));

          Bạckground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main/BackgroundL.png"))); // NOI18N
          getContentPane().add(Bạckground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 770));

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void BtnLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLienHeActionPerformed
        // TODO add your handling code here:
	 AboutUs us = new AboutUs();
	 us.setVisible(true);
	 this.dispose();
    }//GEN-LAST:event_BtnLienHeActionPerformed

    private void btnPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhimActionPerformed
        // TODO add your handling code here:
        ViewQLPHIM phim = new ViewQLPHIM();
        phim.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPhimActionPerformed

    private void BtnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPhongActionPerformed
        // TODO add your handling code here:
        ViewQLPC phongchieu = new ViewQLPC();
        phongchieu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPhongActionPerformed

    private void BtnLichChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLichChieuActionPerformed
        // TODO add your handling code here:
	new Controller.QLLC.CotrollerQLLC();
	this.dispose();
    }//GEN-LAST:event_BtnLichChieuActionPerformed
    /**
     * hien thi form quan ly ban ve
     */
    private void BtnVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVeActionPerformed
        // TODO add your handling code here:
        new FQuanLyVe().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVeActionPerformed

    private void BtnTienIchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTienIchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTienIchActionPerformed
    
    public void setTimeSystem(){
	 Calendar cal = Calendar.getInstance();
	 SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
	 String date = dateFormat.format(cal.getTime());
	 this.lblTimeSystem.setText(date);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /*         * Create and display the form
       */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BtnLichChieu;
     private javax.swing.JButton BtnLienHe;
     private javax.swing.JButton BtnPhong;
     private javax.swing.JButton BtnTienIch;
     private javax.swing.JButton BtnVe;
     private javax.swing.JLabel Bạckground;
     private javax.swing.JButton btnPhim;
     private javax.swing.JLabel lblDateSystem;
     private javax.swing.JLabel lblTimeSystem;
     // End of variables declaration//GEN-END:variables
}
